CREATE TYPE "ServiceActivityType" AS ENUM ('ASSIGNMENT','SITE_VISIT','STATUS_UPDATE','RESOLUTION','NOTE');
CREATE TYPE "ServiceVisitStatus" AS ENUM ('PLANNED','IN_PROGRESS','COMPLETED','CANCELLED');
CREATE TYPE "ServiceFeedbackRating" AS ENUM ('ONE','TWO','THREE','FOUR','FIVE');
ALTER TYPE "SpareMovementType" ADD VALUE IF NOT EXISTS 'REPLACEMENT';
ALTER TYPE "SpareMovementType" ADD VALUE IF NOT EXISTS 'CONSUMED';
CREATE TABLE "ServiceActivity" ("id" TEXT NOT NULL,"serviceRequestId" TEXT NOT NULL,"activityType" "ServiceActivityType" NOT NULL,"notes" TEXT,"fromStatus" "ServiceRequestStatus","toStatus" "ServiceRequestStatus","assignedToId" TEXT,"createdById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ServiceActivity_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ServiceActivity_serviceRequestId_createdAt_idx" ON "ServiceActivity"("serviceRequestId","createdAt");
CREATE INDEX "ServiceActivity_assignedToId_idx" ON "ServiceActivity"("assignedToId");
CREATE TABLE "ServiceSiteVisit" ("id" TEXT NOT NULL,"serviceRequestId" TEXT NOT NULL,"engineerId" TEXT,"visitNumber" INTEGER NOT NULL DEFAULT 1,"scheduledAt" TIMESTAMP(3),"startedAt" TIMESTAMP(3),"completedAt" TIMESTAMP(3),"status" "ServiceVisitStatus" NOT NULL DEFAULT 'PLANNED',"siteContact" TEXT,"findings" TEXT,"workPerformed" TEXT,"issueDescription" TEXT,"photoUrl" TEXT,"latitude" DECIMAL(10,7),"longitude" DECIMAL(10,7),"createdById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ServiceSiteVisit_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ServiceSiteVisit_serviceRequestId_visitNumber_idx" ON "ServiceSiteVisit"("serviceRequestId","visitNumber");
CREATE INDEX "ServiceSiteVisit_engineerId_status_idx" ON "ServiceSiteVisit"("engineerId","status");
CREATE TABLE "ServiceFeedback" ("id" TEXT NOT NULL,"serviceRequestId" TEXT NOT NULL,"rating" "ServiceFeedbackRating" NOT NULL,"comments" TEXT,"customerName" TEXT,"submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ServiceFeedback_pkey" PRIMARY KEY ("id"),CONSTRAINT "ServiceFeedback_serviceRequestId_key" UNIQUE ("serviceRequestId"));
CREATE INDEX "ServiceFeedback_submittedAt_idx" ON "ServiceFeedback"("submittedAt");
CREATE TABLE "ServiceSpareMovement" ("id" TEXT NOT NULL,"serviceRequestId" TEXT NOT NULL,"spareName" TEXT NOT NULL,"partNumber" TEXT,"quantity" DECIMAL(12,3) NOT NULL,"movementType" "SpareMovementType" NOT NULL,"serialNumber" TEXT,"replacedPart" TEXT,"warrantyCovered" BOOLEAN NOT NULL DEFAULT false,"notes" TEXT,"movedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"movedById" TEXT,CONSTRAINT "ServiceSpareMovement_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ServiceSpareMovement_serviceRequestId_movedAt_idx" ON "ServiceSpareMovement"("serviceRequestId","movedAt");
CREATE INDEX "ServiceSpareMovement_partNumber_idx" ON "ServiceSpareMovement"("partNumber");
CREATE TABLE "PreventiveMaintenancePlan" ("id" TEXT NOT NULL,"contractId" TEXT,"customerId" TEXT NOT NULL,"title" TEXT NOT NULL,"frequencyDays" INTEGER NOT NULL,"nextDueDate" TIMESTAMP(3) NOT NULL,"lastCompletedDate" TIMESTAMP(3),"checklist" TEXT,"active" BOOLEAN NOT NULL DEFAULT true,"createdById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PreventiveMaintenancePlan_pkey" PRIMARY KEY ("id"));
CREATE INDEX "PreventiveMaintenancePlan_customerId_active_idx" ON "PreventiveMaintenancePlan"("customerId","active");
CREATE INDEX "PreventiveMaintenancePlan_nextDueDate_idx" ON "PreventiveMaintenancePlan"("nextDueDate");
CREATE TABLE "WarrantyCoverage" ("id" TEXT NOT NULL,"contractId" TEXT NOT NULL,"componentName" TEXT NOT NULL,"coverageType" TEXT NOT NULL,"included" BOOLEAN NOT NULL DEFAULT true,"exclusions" TEXT,"replacementLimit" DECIMAL(15,2),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "WarrantyCoverage_pkey" PRIMARY KEY ("id"));
CREATE INDEX "WarrantyCoverage_contractId_idx" ON "WarrantyCoverage"("contractId");
