import type{Attendance,Department,Employee,HrDashboard,Leave,PayrollRun,PayrollControl}from"../types/hr";
const API=import.meta.env.VITE_API_URL||"http://localhost:5000/api"; const h=(json=false)=>{const t=localStorage.getItem("accessToken");if(!t)throw new Error("Your session has expired. Please sign in again.");return{...(json?{"Content-Type":"application/json"}:{}),Authorization:`Bearer ${t}`}};
async function call<T>(path:string,init?:RequestInit):Promise<T>{const r=await fetch(`${API}/hr${path}`,{...init,headers:{...h(Boolean(init?.body)),...(init?.headers||{})}});const x=await r.json();if(!r.ok)throw new Error(x.message||"HR request failed");return x.data as T}
export const getHrDashboard=()=>call<HrDashboard>("/dashboard"); export const getDepartments=()=>call<Department[]>("/departments"); export const createDepartment=(p:unknown)=>call<Department>("/departments",{method:"POST",body:JSON.stringify(p)}); export const createDesignation=(p:unknown)=>call("/designations",{method:"POST",body:JSON.stringify(p)});
export const getEmployees=(s="")=>call<Employee[]>(`/employees${s.trim()?`?search=${encodeURIComponent(s.trim())}`:""}`); export const createEmployee=(p:unknown)=>call<Employee>("/employees",{method:"POST",body:JSON.stringify(p)}); export const updateEmployee=(id:string,p:unknown)=>call<Employee>(`/employees/${id}`,{method:"PATCH",body:JSON.stringify(p)});
export const getAttendance=()=>call<Attendance[]>("/attendance"); export const recordAttendance=(p:unknown)=>call<Attendance>("/attendance",{method:"POST",body:JSON.stringify(p)});
export const getLeaves=()=>call<Leave[]>("/leaves"); export const createLeave=(p:unknown)=>call<Leave>("/leaves",{method:"POST",body:JSON.stringify(p)}); export const updateLeave=(id:string,p:unknown)=>call<Leave>(`/leaves/${id}`,{method:"PATCH",body:JSON.stringify(p)});
export const setSalary=(id:string,p:unknown)=>call(`/employees/${id}/salary`,{method:"PUT",body:JSON.stringify(p)});
export const getPayroll=()=>call<PayrollRun[]>("/payroll"); export const getPayrollControl=()=>call<PayrollControl>("/payroll/control"); export const createPayroll=(p:unknown)=>call<PayrollRun>("/payroll",{method:"POST",body:JSON.stringify(p)}); export const updatePayroll=(id:string,p:unknown)=>call<PayrollRun>(`/payroll/${id}`,{method:"PATCH",body:JSON.stringify(p)});
