export type AccountType="ASSET"|"LIABILITY"|"EQUITY"|"INCOME"|"EXPENSE"; export type JournalStatus="DRAFT"|"POSTED"|"VOID"; export type VendorBillStatus="DRAFT"|"OPEN"|"PARTIALLY_PAID"|"PAID"|"CANCELLED"; export type ExpenseStatus="DRAFT"|"APPROVED"|"PAID"|"CANCELLED"; export type PaymentMethod="CASH"|"BANK_TRANSFER"|"UPI"|"CHEQUE"|"CARD"|"OTHER"; export type GstType="NONE"|"CGST_SGST"|"IGST";
export interface FinanceAccount{id:string;code:string;name:string;accountType:AccountType;parentId:string|null;description:string|null;isActive:boolean}
export interface JournalLine{id:string;accountId:string;description:string|null;debit:string;credit:string;account:FinanceAccount}
export interface JournalEntry{id:string;journalNumber:string;journalDate:string;description:string;status:JournalStatus;lines:JournalLine[]}
export interface FinanceDashboard{receivable:number;payable:number;invoiced:number;received:number;vendorPaid:number;expenses:number;overdueReceivables:number;overduePayables:number}
export interface Receivable{id:string;invoiceNumber:string;invoiceDate:string;dueDate:string|null;totalAmount:string;paidAmount:string;balanceAmount:string;status:string;customer:{id:string;customerCode:string;companyName:string};payments:Array<{id:string;paymentNumber:string;amount:string;paymentDate:string;method:PaymentMethod}>}
export interface EligibleGrn{id:string;grnNumber:string;invoiceNumber:string|null;receiptDate:string;vendor:{id:string;vendorCode:string;name:string};purchaseOrder:{id:string;poNumber:string;totalAmount:string;currency:string};items:Array<{acceptedQuantity:string;unitCost:string}>}
export interface VendorBill{id:string;billNumber:string;vendorInvoice:string|null;billDate:string;dueDate:string|null;totalAmount:string;paidAmount:string;balanceAmount:string;status:VendorBillStatus;vendor:{id:string;vendorCode:string;name:string};grn:{id:string;grnNumber:string;invoiceNumber:string|null;receiptDate:string}|null;payments:Array<{id:string;paymentNumber:string;amount:string;paymentDate:string;method:PaymentMethod}>}
export interface FinanceExpense{id:string;expenseNumber:string;expenseDate:string;category:string;description:string;amount:string;gstType:GstType|null;gstRate:string;cgstAmount:string;sgstAmount:string;igstAmount:string;taxAmount:string;totalAmount:string;status:ExpenseStatus;paymentMethod:PaymentMethod|null;referenceNumber:string|null;vendor:{id:string;vendorCode:string;name:string}|null}
export interface GstSummary{taxableAmount:number;cgst:number;sgst:number;igst:number;totalGst:number;records:number}
export interface BalanceRow{id:string;code:string;name:string;accountType:AccountType;debit:number;credit:number;balance:number}
