export type SalesOrderStatus = "DRAFT"|"CONFIRMED"|"ADVANCE_PENDING"|"ADVANCE_RECEIVED"|"IN_PRODUCTION"|"READY_FOR_DISPATCH"|"DISPATCHED"|"INSTALLED"|"COMMISSIONED"|"CLOSED"|"CANCELLED"|"IN_PROGRESS"|"READY_TO_INVOICE"|"COMPLETED";
export type InvoiceStatus="DRAFT"|"ISSUED"|"PARTIALLY_PAID"|"PAID"|"OVERDUE"|"CANCELLED";
export type InvoiceType="PROFORMA"|"TAX";
export type PaymentType="ADVANCE"|"MILESTONE"|"FINAL";
export type PaymentMethod="CASH"|"BANK_TRANSFER"|"UPI"|"CHEQUE"|"CARD"|"OTHER";
export type DispatchNoteStatus="DRAFT"|"READY"|"DISPATCHED"|"DELIVERED"|"CANCELLED";
export interface CustomerLite{id:string;customerCode:string;companyName:string;billingAddress?:string|null;shippingAddress?:string|null;}
export interface EligibleQuotation{id:string;quotationNumber:string;status:string;subtotal:string|number;taxPercent:string|number;taxAmount:string|number;totalAmount:string|number;paymentTerms?:string|null;deliveryTerms?:string|null;customerApprovalStatus?:string;estimate:{items:Array<{id:string;description:string;quantity:string|number;unit:string;unitRate:string|number;sortOrder:number}>;lead:{customer?:CustomerLite|null}}}
export interface SalesOrderItem{id:string;lineNumber:number;description:string;quantity:string|number;unit:string;unitPrice:string|number;discountPercent:string|number;taxPercent:string|number;taxableAmount:string|number;taxAmount:string|number;lineTotal:string|number;}
export interface SalesOrder{id:string;salesOrderNumber:string;status:SalesOrderStatus;orderDate:string;customerPoNumber?:string|null;expectedDeliveryDate?:string|null;subtotal:string|number;discountAmount:string|number;taxAmount:string|number;freightAmount:string|number;totalAmount:string|number;advanceAmount?:string|number;advanceDueAmount?:string|number;customer:CustomerLite;quotation?:{quotationNumber:string}|null;items:SalesOrderItem[];invoices?:Array<{id:string;invoiceNumber:string;status:InvoiceStatus;type?:InvoiceType}>;}
export interface SalesPayment{id:string;paymentNumber:string;paymentDate:string;amount:string|number;method:PaymentMethod;type?:PaymentType;referenceNumber?:string|null;invoice?:{invoiceNumber:string}|null;salesOrder?:{salesOrderNumber:string}|null;}
export interface SalesInvoice{id:string;invoiceNumber:string;type:InvoiceType;status:InvoiceStatus;invoiceDate:string;dueDate?:string|null;subtotal:string|number;discountAmount:string|number;taxAmount:string|number;freightAmount:string|number;totalAmount:string|number;paidAmount:string|number;balanceAmount:string|number;customer:CustomerLite;salesOrder:{id:string;salesOrderNumber:string};payments:SalesPayment[];}
export interface SalesDispatchNote{id:string;dispatchNoteNumber:string;status:DispatchNoteStatus;dispatchDate?:string|null;destination?:string|null;transporterName?:string|null;vehicleNumber?:string|null;lrNumber?:string|null;packageCount:number;salesOrder:{id:string;salesOrderNumber:string;customer?:CustomerLite};items:Array<{id:string;lineNumber:number;description:string;quantity:string|number;unit:string;serialNumber?:string|null;packageDetails?:string|null}>;}
export interface SalesEWayBill{id:string;eWayBillNumber:string;salesOrderId:string;dispatchNoteId?:string|null;vehicleNumber?:string|null;transporterName?:string|null;distanceKm?:string|number|null;validUntil?:string|null;}
export interface CreateSalesOrderPayload{quotationId?:string;customerId:string;customerPoNumber?:string;customerPoDate?:string;expectedDeliveryDate?:string;freightAmount?:number;paymentTerms?:string;deliveryTerms?:string;billingAddress?:string;shippingAddress?:string;notes?:string;advanceDueAmount?:number;items:Array<{lineNumber:number;description:string;quantity:number;unit:string;unitPrice:number;discountPercent?:number;taxPercent?:number;remarks?:string}>}
