import type { Request,Response } from "express";
import { randomUUID } from "crypto";
import { prisma } from "../config/database.js";
import * as v from "../utils/finance-validation.js";
type AR=Request & {auth?:{userId?:string}};
const fail=(res:Response,e:unknown,m:string)=>{console.error(e);res.status(500).json({success:false,message:m})};
const uid=(p:string)=>`${p}-${new Date().getFullYear()}-${randomUUID().slice(0,8).toUpperCase()}`;
const audit=async(userId:string|undefined,action:string,entity:string,entityId:string,newValues:unknown)=>{await prisma.auditLog.create({data:{userId:userId??null,action,entity,entityId,newValues:newValues as object}}).catch(()=>undefined)};

export const dashboard=async(_r:Request,res:Response)=>{try{
 const [inv,bills,expenses]=await Promise.all([
  prisma.salesInvoice.findMany({where:{status:{not:"CANCELLED"}},select:{totalAmount:true,paidAmount:true,balanceAmount:true,status:true,dueDate:true}}),
  prisma.vendorBill.findMany({where:{status:{not:"CANCELLED"}},select:{totalAmount:true,paidAmount:true,balanceAmount:true,status:true,dueDate:true}}),
  prisma.financeExpense.findMany({where:{status:{not:"CANCELLED"}},select:{totalAmount:true,status:true}})
 ]);
 const n=(x:unknown)=>Number(x??0);
 res.json({success:true,data:{
  receivable:inv.reduce((a,x)=>a+n(x.balanceAmount),0),
  payable:bills.reduce((a,x)=>a+n(x.balanceAmount),0),
  invoiced:inv.reduce((a,x)=>a+n(x.totalAmount),0),
  received:inv.reduce((a,x)=>a+n(x.paidAmount),0),
  vendorPaid:bills.reduce((a,x)=>a+n(x.paidAmount),0),
  expenses:expenses.reduce((a,x)=>a+n(x.totalAmount),0),
  overdueReceivables:inv.filter(x=>x.dueDate&&x.dueDate<new Date()&&n(x.balanceAmount)>0).reduce((a,x)=>a+n(x.balanceAmount),0),
  overduePayables:bills.filter(x=>x.dueDate&&x.dueDate<new Date()&&n(x.balanceAmount)>0).reduce((a,x)=>a+n(x.balanceAmount),0)
 }});
}catch(e){fail(res,e,"Unable to load finance dashboard")}};

export const listAccounts=async(_r:Request,res:Response)=>{try{res.json({success:true,data:await prisma.financeAccount.findMany({orderBy:[{accountType:"asc"},{code:"asc"}]})})}catch(e){fail(res,e,"Unable to load accounts")}};
export const createAccount=async(req:AR,res:Response)=>{try{const p=v.accountSchema.safeParse(req.body);if(!p.success)return void res.status(400).json({success:false,message:"Invalid account",errors:p.error.flatten().fieldErrors});const data=await prisma.financeAccount.create({data:{...p.data,parentId:p.data.parentId??null,description:p.data.description??null}});await audit(req.auth?.userId,"CREATE","FinanceAccount",data.id,data);res.status(201).json({success:true,data})}catch(e){fail(res,e,"Unable to create account")}};

const journalInclude={lines:{include:{account:true}},createdBy:{select:{id:true,employeeCode:true,firstName:true,lastName:true}},postedBy:{select:{id:true,employeeCode:true,firstName:true,lastName:true}}} as const;
export const listJournals=async(_r:Request,res:Response)=>{try{res.json({success:true,data:await prisma.financeJournalEntry.findMany({include:journalInclude,orderBy:{journalDate:"desc"}})})}catch(e){fail(res,e,"Unable to load journals")}};
export const createJournal=async(req:AR,res:Response)=>{try{const p=v.journalSchema.safeParse(req.body);if(!p.success)return void res.status(400).json({success:false,message:"Invalid journal",errors:p.error.flatten().fieldErrors});const debit=p.data.lines.reduce((a,x)=>a+x.debit,0),credit=p.data.lines.reduce((a,x)=>a+x.credit,0);if(Math.abs(debit-credit)>.005||debit<=0)return void res.status(400).json({success:false,message:"Journal debit and credit must be equal and greater than zero"});const data=await prisma.financeJournalEntry.create({data:{journalNumber:uid("JV"),journalDate:p.data.journalDate?new Date(p.data.journalDate):new Date(),description:p.data.description,referenceType:p.data.referenceType??null,referenceId:p.data.referenceId??null,createdById:req.auth?.userId??null,lines:{create:p.data.lines.map(x=>({accountId:x.accountId,description:x.description??null,debit:x.debit,credit:x.credit}))}},include:journalInclude});await audit(req.auth?.userId,"CREATE","FinanceJournalEntry",data.id,data);res.status(201).json({success:true,data})}catch(e){fail(res,e,"Unable to create journal")}};
export const postJournal=async(req:AR,res:Response)=>{try{const id=String(req.params.id);const old=await prisma.financeJournalEntry.findUnique({where:{id}});if(!old)return void res.status(404).json({success:false,message:"Journal not found"});if(old.status!=="DRAFT")return void res.status(400).json({success:false,message:"Only draft journals can be posted"});const data=await prisma.financeJournalEntry.update({where:{id},data:{status:"POSTED",postedAt:new Date(),postedById:req.auth?.userId??null},include:journalInclude});await audit(req.auth?.userId,"POST","FinanceJournalEntry",id,data);res.json({success:true,data})}catch(e){fail(res,e,"Unable to post journal")}};

export const receivables=async(_r:Request,res:Response)=>{try{const data=await prisma.salesInvoice.findMany({where:{status:{not:"CANCELLED"}},include:{customer:{select:{id:true,customerCode:true,companyName:true}},payments:true},orderBy:{invoiceDate:"desc"}});res.json({success:true,data})}catch(e){fail(res,e,"Unable to load receivables")}};

const billInclude={vendor:true,grn:{select:{id:true,grnNumber:true,invoiceNumber:true,receiptDate:true}},payments:true} as const;
export const eligibleGrns=async(_r:Request,res:Response)=>{try{const data=await prisma.goodsReceiptNote.findMany({where:{postedAt:{not:null},status:{in:["ACCEPTED","PARTIALLY_ACCEPTED"]},vendorBill:null},include:{vendor:true,purchaseOrder:{select:{id:true,poNumber:true,totalAmount:true,currency:true}},items:true},orderBy:{receiptDate:"desc"}});res.json({success:true,data})}catch(e){fail(res,e,"Unable to load eligible GRNs")}};
export const listBills=async(_r:Request,res:Response)=>{try{res.json({success:true,data:await prisma.vendorBill.findMany({include:billInclude,orderBy:{billDate:"desc"}})})}catch(e){fail(res,e,"Unable to load vendor bills")}};
export const createBill=async(req:AR,res:Response)=>{try{const p=v.vendorBillSchema.safeParse(req.body);if(!p.success)return void res.status(400).json({success:false,message:"Invalid vendor bill",errors:p.error.flatten().fieldErrors});const grn=await prisma.goodsReceiptNote.findUnique({where:{id:p.data.grnId},include:{items:true,purchaseOrder:true,vendorBill:true}});if(!grn)return void res.status(404).json({success:false,message:"GRN not found"});if(!grn.postedAt||!["ACCEPTED","PARTIALLY_ACCEPTED"].includes(grn.status))return void res.status(400).json({success:false,message:"Only posted accepted GRNs can create vendor bills"});if(grn.vendorBill)return void res.status(409).json({success:false,message:"Vendor bill already exists for this GRN"});const amount=grn.items.reduce((a,x)=>a+Number(x.acceptedQuantity)*Number(x.unitCost),0);if(amount<=0)return void res.status(400).json({success:false,message:"Accepted GRN value must be greater than zero"});const data=await prisma.vendorBill.create({data:{billNumber:uid("VB"),vendorId:grn.vendorId,grnId:grn.id,vendorInvoice:grn.invoiceNumber,billDate:grn.receiptDate,dueDate:p.data.dueDate?new Date(p.data.dueDate):null,currency:grn.purchaseOrder.currency,totalAmount:amount,balanceAmount:amount,notes:p.data.notes??null,createdById:req.auth?.userId??null},include:billInclude});await audit(req.auth?.userId,"CREATE","VendorBill",data.id,data);res.status(201).json({success:true,data})}catch(e){fail(res,e,"Unable to create vendor bill")}};

export const createVendorPayment=async(req:AR,res:Response)=>{try{const p=v.vendorPaymentSchema.safeParse(req.body);if(!p.success)return void res.status(400).json({success:false,message:"Invalid vendor payment",errors:p.error.flatten().fieldErrors});const bill=await prisma.vendorBill.findUnique({where:{id:p.data.vendorBillId}});if(!bill)return void res.status(404).json({success:false,message:"Vendor bill not found"});if(["PAID","CANCELLED"].includes(bill.status))return void res.status(400).json({success:false,message:"Bill is not payable"});if(p.data.amount>Number(bill.balanceAmount)+.005)return void res.status(400).json({success:false,message:"Payment cannot exceed bill balance"});const paymentId=randomUUID(),approvalId=randomUUID(),now=new Date(),paymentNumber=uid("VP");const result=await prisma.$transaction(async tx=>{await tx.$executeRawUnsafe(`INSERT INTO "VendorPayment" ("id","paymentNumber","vendorBillId","vendorId","paymentDate","amount","method","referenceNumber","notes","recordedById","createdAt") VALUES ($1,$2,$3,$4,$5,$6,$7::"PaymentMethod",$8,$9,$10,$11)`,paymentId,paymentNumber,bill.id,bill.vendorId,p.data.paymentDate?new Date(p.data.paymentDate):now,p.data.amount,p.data.method,p.data.referenceNumber??null,p.data.notes??null,req.auth?.userId??null,now);await tx.$executeRawUnsafe(`INSERT INTO "VendorPaymentApproval" ("id","vendorPaymentId","status","requestedAt","createdAt","updatedAt") VALUES ($1,$2,'PENDING',$3,$3,$3)`,approvalId,paymentId,now);return {id:paymentId,paymentNumber,approvalId,status:"PENDING"}});await audit(req.auth?.userId,"CREATE","VendorPayment",result.id,result);res.status(201).json({success:true,data:result})}catch(e){fail(res,e,"Unable to request vendor payment")}};

export const listExpenses=async(_r:Request,res:Response)=>{try{res.json({success:true,data:await prisma.financeExpense.findMany({include:{vendor:true},orderBy:{expenseDate:"desc"}})})}catch(e){fail(res,e,"Unable to load expenses")}};
export const createExpense=async(req:AR,res:Response)=>{try{
 const p=v.expenseSchema.safeParse(req.body);
 if(!p.success)return void res.status(400).json({success:false,message:"Invalid expense",errors:p.error.flatten().fieldErrors});
 const x=p.data,base=x.amount,rate=x.gstRate??0,type=x.gstType??"NONE";
 let cgst=0,sgst=0,igst=0;
 if(type==="CGST_SGST"){cgst=base*(rate/2)/100;sgst=base*(rate/2)/100}
 if(type==="IGST")igst=base*rate/100;
 const tax=cgst+sgst+igst;
 const data=await prisma.financeExpense.create({data:{expenseNumber:uid("EXP"),expenseDate:x.expenseDate?new Date(x.expenseDate):new Date(),category:x.category,description:x.description,vendorId:x.vendorId??null,amount:base,gstType:type,gstRate:rate,cgstAmount:cgst,sgstAmount:sgst,igstAmount:igst,taxAmount:tax,totalAmount:base+tax,paymentMethod:x.paymentMethod??null,referenceNumber:x.referenceNumber??null,notes:x.notes??null,createdById:req.auth?.userId??null}});
 await audit(req.auth?.userId,"CREATE","FinanceExpense",data.id,data);res.status(201).json({success:true,data})
}catch(e){fail(res,e,"Unable to create expense")}};

export const updateExpense=async(req:AR,res:Response)=>{try{const p=v.expenseUpdateSchema.safeParse(req.body);if(!p.success)return void res.status(400).json({success:false,message:"Invalid expense status"});const id=String(req.params.id);
const updateData = {
  status:p.data.status,
  ...(p.data.status==="APPROVED"?{approvedById:req.auth?.userId??null,approvedAt:new Date()}:{}),
  ...(p.data.status==="PAID"?{paidAt:new Date()}:{}),
};
const data=await prisma.financeExpense.update({where:{id},data:updateData});await audit(req.auth?.userId,"UPDATE","FinanceExpense",id,data);res.json({success:true,data})}catch(e){fail(res,e,"Unable to update expense")}};

async function balances(){
 const accounts=await prisma.financeAccount.findMany({where:{isActive:true},include:{journalLines:{where:{journal:{status:"POSTED"}},select:{debit:true,credit:true}}},orderBy:{code:"asc"}});
 return accounts.map(a=>{const debit=a.journalLines.reduce((s,x)=>s+Number(x.debit),0),credit=a.journalLines.reduce((s,x)=>s+Number(x.credit),0);return{id:a.id,code:a.code,name:a.name,accountType:a.accountType,debit,credit,balance:["ASSET","EXPENSE"].includes(a.accountType)?debit-credit:credit-debit}});
}
export const trialBalance=async(_r:Request,res:Response)=>{try{res.json({success:true,data:await balances()})}catch(e){fail(res,e,"Unable to load trial balance")}};
export const profitLoss=async(_r:Request,res:Response)=>{try{const b=await balances(),income=b.filter(x=>x.accountType==="INCOME").reduce((a,x)=>a+x.balance,0),expense=b.filter(x=>x.accountType==="EXPENSE").reduce((a,x)=>a+x.balance,0);res.json({success:true,data:{income,expense,profit:income-expense,accounts:b.filter(x=>["INCOME","EXPENSE"].includes(x.accountType))}})}catch(e){fail(res,e,"Unable to load profit and loss")}};
export const balanceSheet=async(_r:Request,res:Response)=>{try{const b=await balances(),sum=(t:string)=>b.filter(x=>x.accountType===t).reduce((a,x)=>a+x.balance,0);res.json({success:true,data:{assets:sum("ASSET"),liabilities:sum("LIABILITY"),equity:sum("EQUITY"),accounts:b.filter(x=>["ASSET","LIABILITY","EQUITY"].includes(x.accountType))}})}catch(e){fail(res,e,"Unable to load balance sheet")}};

export const gstSummary=async(_r:Request,res:Response)=>{try{
 const [rows,invoices]=await Promise.all([prisma.financeExpense.findMany({where:{status:{not:"CANCELLED"}},select:{amount:true,taxAmount:true,cgstAmount:true,sgstAmount:true,igstAmount:true}}),prisma.salesInvoice.findMany({where:{status:{not:"CANCELLED"}},select:{subtotal:true,taxAmount:true,totalAmount:true}})]);
 const n=(v:unknown)=>Number(v??0); const inputTax=rows.reduce((a,x)=>a+n(x.taxAmount),0),outputTax=invoices.reduce((a,x)=>a+n(x.taxAmount),0);
 res.json({success:true,data:{taxableAmount:rows.reduce((a,x)=>a+n(x.amount),0),cgst:rows.reduce((a,x)=>a+n(x.cgstAmount),0),sgst:rows.reduce((a,x)=>a+n(x.sgstAmount),0),igst:rows.reduce((a,x)=>a+n(x.igstAmount),0),inputGst:inputTax,outputGst:outputTax,netGstPayable:outputTax-inputTax,totalGst:inputTax,records:rows.length,invoiceRecords:invoices.length}})
}catch(e){fail(res,e,"Unable to load GST summary")}};


// ============================================================
// MODULE 15 - Finance extensions
// ============================================================
export const createCustomerReceipt=async(req:AR,res:Response)=>{try{
 const invoiceId=String(req.body.invoiceId||""); const amount=Number(req.body.amount||0); const method=String(req.body.method||"BANK_TRANSFER");
 if(!invoiceId||amount<=0)return res.status(400).json({success:false,message:"Invoice and a positive receipt amount are required"});
 const inv=await prisma.salesInvoice.findUnique({where:{id:invoiceId}}); if(!inv)return res.status(404).json({success:false,message:"Invoice not found"});
 if(["CANCELLED","PAID"].includes(inv.status))return res.status(400).json({success:false,message:"Invoice is not receivable"});
 if(amount>Number(inv.balanceAmount)+.005)return res.status(400).json({success:false,message:"Receipt cannot exceed invoice balance"});
 const receiptId=randomUUID(), paymentId=randomUUID(), now=new Date(), receiptNumber=uid("RCT"), paymentNumber=uid("PAY");
 const paid=Number(inv.paidAmount)+amount, balance=Math.max(0,Number(inv.totalAmount)-paid), status=balance<=.005?"PAID":"PARTIALLY_PAID";
 const data=await prisma.$transaction(async tx=>{
  await tx.$executeRawUnsafe(`INSERT INTO "SalesPayment" ("id","invoiceId","paymentNumber","paymentDate","amount","method","referenceNumber","notes","recordedById","createdAt") VALUES ($1,$2,$3,$4,$5,$6::"PaymentMethod",$7,$8,$9,$10)`,paymentId,invoiceId,paymentNumber,req.body.paymentDate?new Date(req.body.paymentDate):now,amount,method,req.body.referenceNumber||null,req.body.notes||null,req.auth?.userId||null,now);
  await tx.$executeRawUnsafe(`UPDATE "SalesInvoice" SET "paidAmount"=$1,"balanceAmount"=$2,"status"=$3::"InvoiceStatus","paidAt"=CASE WHEN $2<=0 THEN $4 ELSE "paidAt" END,"updatedAt"=$4 WHERE "id"=$5`,paid,balance,status,now,invoiceId);
  await tx.$executeRawUnsafe(`INSERT INTO "FinanceReceipt" ("id","receiptNumber","invoiceId","customerId","receiptDate","amount","method","referenceNumber","notes","createdById","createdAt") VALUES ($1,$2,$3,$4,$5,$6,$7::"PaymentMethod",$8,$9,$10,$11)`,receiptId,receiptNumber,invoiceId,inv.customerId,req.body.paymentDate?new Date(req.body.paymentDate):now,amount,method,req.body.referenceNumber||null,req.body.notes||null,req.auth?.userId||null,now);
  return {id:receiptId,receiptNumber,paymentNumber,invoiceId,amount,balance,status};
 });
 await audit(req.auth?.userId,"CREATE","FinanceReceipt",data.id,data); res.status(201).json({success:true,data});
}catch(e){fail(res,e,"Unable to record customer receipt")}};

export const listReceipts=async(_r:Request,res:Response)=>{try{const data=await prisma.$queryRawUnsafe(`SELECT r.*,i."invoiceNumber",c."companyName" AS "customerName" FROM "FinanceReceipt" r JOIN "SalesInvoice" i ON i."id"=r."invoiceId" JOIN "Customer" c ON c."id"=r."customerId" ORDER BY r."receiptDate" DESC`);res.json({success:true,data})}catch(e){fail(res,e,"Unable to load receipts")}};

export const createPaymentFollowUp=async(req:AR,res:Response)=>{try{const invoiceId=String(req.body.invoiceId||"");if(!invoiceId)return res.status(400).json({success:false,message:"Invoice is required"});const id=randomUUID(),now=new Date();await prisma.$executeRawUnsafe(`INSERT INTO "FinancePaymentFollowUp" ("id","invoiceId","followUpDate","nextFollowUpDate","status","notes","assignedToId","createdById","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5::"FinanceFollowUpStatus",$6,$7,$8,$9,$9)`,id,invoiceId,req.body.followUpDate?new Date(req.body.followUpDate):now,req.body.nextFollowUpDate?new Date(req.body.nextFollowUpDate):null,req.body.status||"OPEN",req.body.notes||null,req.body.assignedToId||null,req.auth?.userId||null,now);res.status(201).json({success:true,data:{id}})}catch(e){fail(res,e,"Unable to create payment follow-up")}};
export const listPaymentFollowUps=async(_r:Request,res:Response)=>{try{const data=await prisma.$queryRawUnsafe(`SELECT f.*,i."invoiceNumber",c."companyName" AS "customerName" FROM "FinancePaymentFollowUp" f JOIN "SalesInvoice" i ON i."id"=f."invoiceId" JOIN "Customer" c ON c."id"=i."customerId" ORDER BY f."nextFollowUpDate" NULLS LAST,f."followUpDate" DESC`);res.json({success:true,data})}catch(e){fail(res,e,"Unable to load payment follow-ups")}};

export const listVendorPaymentApprovals=async(_r:Request,res:Response)=>{try{const data=await prisma.$queryRawUnsafe(`SELECT a.*,p."paymentNumber",p."amount",p."paymentDate",v."name" AS "vendorName",b."billNumber" FROM "VendorPaymentApproval" a JOIN "VendorPayment" p ON p."id"=a."vendorPaymentId" JOIN "Vendor" v ON v."id"=p."vendorId" JOIN "VendorBill" b ON b."id"=p."vendorBillId" ORDER BY a."requestedAt" DESC`);res.json({success:true,data})}catch(e){fail(res,e,"Unable to load payment approvals")}};
export const approveVendorPayment=async(req:AR,res:Response)=>{try{const approvalId=String(req.params.id),decision=req.body.decision;const row=await prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "VendorPaymentApproval" WHERE "id"=$1`,approvalId);if(!row[0])return res.status(404).json({success:false,message:"Approval request not found"});if(row[0].status!=="PENDING")return res.status(400).json({success:false,message:"Approval is already processed"});const now=new Date();if(decision==="REJECTED"){await prisma.$executeRawUnsafe(`UPDATE "VendorPaymentApproval" SET "status"='REJECTED',"approvedById"=$1,"approvedAt"=$2,"rejectionReason"=$3,"updatedAt"=$2 WHERE "id"=$4`,req.auth?.userId||null,now,req.body.rejectionReason||"Rejected",approvalId);return res.json({success:true,data:{status:"REJECTED"}})}if(decision!=="APPROVED")return res.status(400).json({success:false,message:"Decision must be APPROVED or REJECTED"});
 await prisma.$transaction(async tx=>{const p=await tx.$queryRawUnsafe<any[]>(`SELECT p.*,b."totalAmount",b."paidAmount",b."balanceAmount",b."status" AS "billStatus" FROM "VendorPayment" p JOIN "VendorBill" b ON b."id"=p."vendorBillId" WHERE p."id"=$1`,row[0].vendorPaymentId);if(!p[0])throw new Error("Vendor payment not found");const pay=p[0];const newPaid=Number(pay.paidAmount)+Number(pay.amount),newBal=Math.max(0,Number(pay.balanceAmount)-Number(pay.amount));await tx.$executeRawUnsafe(`UPDATE "VendorBill" SET "paidAmount"=$1,"balanceAmount"=$2,"status"=$3::"VendorBillStatus","updatedAt"=$4 WHERE "id"=$5`,newPaid,newBal,newBal<=.005?"PAID":"PARTIALLY_PAID",now,pay.vendorBillId);await tx.$executeRawUnsafe(`UPDATE "VendorPaymentApproval" SET "status"='APPROVED',"approvedById"=$1,"approvedAt"=$2,"updatedAt"=$2 WHERE "id"=$3`,req.auth?.userId||null,now,approvalId)});res.json({success:true,data:{status:"APPROVED"}})
}catch(e){fail(res,e,"Unable to process payment approval")}};

export const cashFlow=async(_r:Request,res:Response)=>{try{const [receipts,payments,expenses]=await Promise.all([prisma.salesPayment.aggregate({_sum:{amount:true}}),prisma.vendorPayment.aggregate({_sum:{amount:true}}),prisma.financeExpense.aggregate({where:{status:"PAID"},_sum:{totalAmount:true}})]);const inflow=Number(receipts._sum.amount||0),outflow=Number(payments._sum.amount||0)+Number(expenses._sum.totalAmount||0);res.json({success:true,data:{inflow,outflow,netCashFlow:inflow-outflow,customerReceipts:Number(receipts._sum.amount||0),vendorPayments:Number(payments._sum.amount||0),operatingExpenses:Number(expenses._sum.totalAmount||0)}})}catch(e){fail(res,e,"Unable to load cash flow")}};

export const customerProfitability=async(_r:Request,res:Response)=>{try{const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT c."id",c."customerCode",c."companyName",COALESCE((SELECT SUM(i."totalAmount") FROM "SalesInvoice" i WHERE i."customerId"=c."id" AND i."status"<>'CANCELLED'),0) AS revenue,COALESCE((SELECT SUM(p."actualCost") FROM "Project" p WHERE p."customerId"=c."id"),0) AS cost FROM "Customer" c ORDER BY revenue DESC`);res.json({success:true,data:rows.map(x=>({...x,revenue:Number(x.revenue||0),cost:Number(x.cost||0),profit:Number(x.revenue||0)-Number(x.cost||0)}))})}catch(e){fail(res,e,"Unable to load customer profitability")}};
export const projectProfitability=async(_r:Request,res:Response)=>{try{const rows=await prisma.project.findMany({select:{id:true,projectNumber:true,title:true,revenueAmount:true,actualCost:true,progressPercent:true},orderBy:{createdAt:"desc"}});res.json({success:true,data:rows.map(x=>({...x,revenue:Number(x.revenueAmount),cost:Number(x.actualCost),profit:Number(x.revenueAmount)-Number(x.actualCost)}))})}catch(e){fail(res,e,"Unable to load project profitability")}};
export const productProfitability=async(_r:Request,res:Response)=>{try{const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT x."description" AS "productName",SUM(x."quantity") AS quantity,SUM(x."lineTotal") AS revenue,COALESCE(fc."standardCost",0) AS "standardCost" FROM "SalesInvoiceItem" x JOIN "SalesInvoice" i ON i."id"=x."invoiceId" LEFT JOIN "FinanceProductCost" fc ON LOWER(fc."productName")=LOWER(x."description") AND fc."active"=true WHERE i."status"<>'CANCELLED' GROUP BY x."description",fc."standardCost" ORDER BY revenue DESC`);res.json({success:true,data:rows.map(x=>{const qty=Number(x.quantity||0),rev=Number(x.revenue||0),cost=qty*Number(x.standardCost||0);return {...x,quantity:qty,revenue:rev,cost,profit:rev-cost}})})}catch(e){fail(res,e,"Unable to load product profitability")}};

export const revenueRecognitions=async(_r:Request,res:Response)=>{try{const data=await prisma.$queryRawUnsafe(`SELECT r.*,p."projectNumber",p."title" AS "projectTitle" FROM "FinanceRevenueRecognition" r LEFT JOIN "Project" p ON p."id"=r."projectId" ORDER BY r."recognitionDate" DESC`);res.json({success:true,data})}catch(e){fail(res,e,"Unable to load revenue recognition")}};
export const createRevenueRecognition=async(req:AR,res:Response)=>{try{const type=String(req.body.recognitionType||"");const projectId=req.body.projectId||null;let amount=Number(req.body.amount||0),percentage=req.body.percentage!=null?Number(req.body.percentage):null;if(!["MILESTONE","PERCENTAGE_COMPLETION","DISPATCH","COMMISSIONING"].includes(type))return res.status(400).json({success:false,message:"Invalid recognition type"});if(type==="PERCENTAGE_COMPLETION"&&projectId&&percentage!=null){const p=await prisma.project.findUnique({where:{id:projectId},select:{revenueAmount:true}});amount=Number(p?.revenueAmount||0)*percentage/100}if(amount<=0)return res.status(400).json({success:false,message:"Recognition amount must be greater than zero"});const id=randomUUID(),now=new Date(),number=uid("REV");await prisma.$executeRawUnsafe(`INSERT INTO "FinanceRevenueRecognition" ("id","recognitionNumber","recognitionType","recognitionDate","projectId","salesOrderId","invoiceId","milestoneId","percentage","amount","notes","createdById","createdAt") VALUES ($1,$2,$3::"FinanceRecognitionType",$4,$5,$6,$7,$8,$9,$10,$11,$12,$4)`,id,number,type,req.body.recognitionDate?new Date(req.body.recognitionDate):now,projectId,req.body.salesOrderId||null,req.body.invoiceId||null,req.body.milestoneId||null,percentage,amount,req.body.notes||null,req.auth?.userId||null);res.status(201).json({success:true,data:{id,recognitionNumber:number,amount}})}catch(e){fail(res,e,"Unable to create revenue recognition")}};

export const tdsSummary=async(_r:Request,res:Response)=>{try{const rows=await prisma.$queryRawUnsafe<any[]>(`SELECT "partyType","tdsSection","status",SUM("taxableAmount") AS "taxableAmount",SUM("tdsAmount") AS "tdsAmount",COUNT(*)::int AS records FROM "TdsRecord" GROUP BY "partyType","tdsSection","status" ORDER BY "partyType","tdsSection"`);res.json({success:true,data:rows})}catch(e){fail(res,e,"Unable to load TDS summary")}};
export const createTds=async(req:AR,res:Response)=>{try{const taxable=Number(req.body.taxableAmount||0),rate=Number(req.body.rate||0);if(taxable<=0||rate<0)return res.status(400).json({success:false,message:"Valid taxable amount and rate are required"});const id=randomUUID(),amount=taxable*rate/100,now=new Date();await prisma.$executeRawUnsafe(`INSERT INTO "TdsRecord" ("id","partyType","partyId","documentType","documentId","tdsSection","rate","taxableAmount","tdsAmount","deductedAt","status","notes","createdById","createdAt") VALUES ($1,$2::"FinancePartyType",$3,$4,$5,$6,$7,$8,$9,$10,'DEDUCTED',$11,$12,$10)`,id,req.body.partyType,req.body.partyId,req.body.documentType,req.body.documentId,req.body.tdsSection,rate,taxable,amount,req.body.deductedAt?new Date(req.body.deductedAt):now,req.body.notes||null,req.auth?.userId||null);res.status(201).json({success:true,data:{id,taxableAmount:taxable,tdsAmount:amount}})}catch(e){fail(res,e,"Unable to create TDS record")}};
export const createProductCost=async(req:AR,res:Response)=>{try{const productName=String(req.body.productName||"").trim(),standardCost=Number(req.body.standardCost||0);if(!productName||standardCost<0)return res.status(400).json({success:false,message:"Product name and non-negative standard cost are required"});const id=randomUUID(),now=new Date();await prisma.$executeRawUnsafe(`INSERT INTO "FinanceProductCost" ("id","productName","standardCost","currency","active","createdAt","updatedAt") VALUES ($1,$2,$3,$4,true,$5,$5) ON CONFLICT ("productName") DO UPDATE SET "standardCost"=EXCLUDED."standardCost","active"=true,"updatedAt"=EXCLUDED."updatedAt"`,id,productName,standardCost,req.body.currency||"INR",now);res.status(201).json({success:true,data:{productName,standardCost}})}catch(e){fail(res,e,"Unable to save product cost")}};
