import { randomUUID } from "node:crypto";
import type { Request, Response } from "express";
import { prisma } from "../config/database.js";
import {
 createJobCardSchema,createMachineSchema,createProductionOrderSchema,createWorkCenterSchema,downtimeSchema,
 materialMovementSchema,traceabilitySchema,updateJobCardSchema,updateProductionOperationSchema,updateProductionOrderSchema,
} from "../utils/production-validation.js";
type AR=Request&{auth?:{userId:string}};
const asDate=(v?:string)=>v?new Date(v):null;
const include={quotation:{include:{estimate:{include:{lead:{include:{customer:true}}}}}},assignedTo:{select:{id:true,employeeCode:true,firstName:true,lastName:true}},operations:{include:{workCenterRef:true,machine:true,assignedTo:{select:{id:true,employeeCode:true,firstName:true,lastName:true}},jobCards:{include:{assignedTo:{select:{id:true,employeeCode:true,firstName:true,lastName:true}}},orderBy:{createdAt:"desc" as const}}},orderBy:{sequence:"asc" as const}},materialMovements:{include:{inventoryItem:{select:{id:true,itemCode:true,name:true,unit:true}}},orderBy:{createdAt:"desc" as const}},traceabilityRecords:{orderBy:{createdAt:"desc" as const}},downtimeRecords:{orderBy:{startedAt:"desc" as const}}} as const;
async function recalc(tx:any,orderId:string){const ops=await tx.productionOperation.findMany({where:{productionOrderId:orderId},select:{status:true,producedQuantity:true,rejectedQuantity:true,scrapQuantity:true,reworkQuantity:true,downtimeMinutes:true}});const done=ops.filter((o:any)=>o.status==="COMPLETED"||o.status==="SKIPPED").length;const progress=ops.length?Math.round(done/ops.length*100):0;const produced=ops.reduce((m:number,o:any)=>Math.max(m,Number(o.producedQuantity)),0);const rejected=ops.reduce((s:number,o:any)=>s+Number(o.rejectedQuantity),0);const scrap=ops.reduce((s:number,o:any)=>s+Number(o.scrapQuantity),0);await tx.productionOrder.update({where:{id:orderId},data:{progressPercent:progress,producedQuantity:produced,rejectedQuantity:rejected,scrapQuantity:scrap,...(progress===100?{status:"COMPLETED",actualEndDate:new Date()}:{})}});}
const fail=(res:Response,e:unknown,msg:string)=>{console.error(msg,e);res.status(500).json({success:false,message:msg});};
export const listProductionOrdersController=async(req:Request,res:Response)=>{try{const search=typeof req.query.search==="string"?req.query.search.trim():"";const data=await prisma.productionOrder.findMany({...(search?{where:{OR:[{productionNumber:{contains:search,mode:"insensitive" as const}},{title:{contains:search,mode:"insensitive" as const}},{quotation:{quotationNumber:{contains:search,mode:"insensitive" as const}}},{quotation:{estimate:{lead:{customer:{companyName:{contains:search,mode:"insensitive" as const}}}}}}]}}:{}),include,orderBy:{createdAt:"desc"}});res.json({success:true,data});}catch(e){fail(res,e,"Unable to load production orders");}};
export const getProductionOrderController=async(req:Request,res:Response)=>{try{const data=await prisma.productionOrder.findUnique({where:{id:String(req.params.id)},include});if(!data){res.status(404).json({success:false,message:"Production order was not found"});return;}res.json({success:true,data});}catch(e){fail(res,e,"Unable to load production order");}};
export const createProductionOrderController=async(req:AR,res:Response)=>{try{const v=createProductionOrderSchema.safeParse(req.body);if(!v.success){res.status(400).json({success:false,message:"Please correct the production order fields",errors:v.error.flatten().fieldErrors});return;}const d=v.data;const q=await prisma.quotation.findUnique({where:{id:d.quotationId},select:{id:true,status:true}});if(!q){res.status(404).json({success:false,message:"Quotation was not found"});return;}if(!["ACCEPTED","CONVERTED"].includes(q.status)){res.status(400).json({success:false,message:"Only an accepted quotation can create a production order"});return;}if(await prisma.productionOrder.findFirst({where:{quotationId:q.id},select:{id:true}})){res.status(409).json({success:false,message:"A production order already exists for this quotation"});return;}const settings=await prisma.companySettings.findFirst({select:{productionPrefix:true}});const number=`${settings?.productionPrefix||"PRO"}-${new Date().getFullYear()}-${randomUUID().slice(0,8).toUpperCase()}`;const data=await prisma.$transaction(async tx=>{const created=await tx.productionOrder.create({data:{productionNumber:number,quotationId:d.quotationId,title:d.title,priority:d.priority,quantity:d.quantity,unit:d.unit,plannedStartDate:asDate(d.plannedStartDate),plannedEndDate:asDate(d.plannedEndDate),assignedToId:d.assignedToId??null,createdById:req.auth?.userId??null,notes:d.notes??null,operations:{create:d.operations.map((o,i)=>({sequence:i+1,name:o.name,workCenter:o.workCenter??null,workCenterId:o.workCenterId??null,machineId:o.machineId??null,assignedToId:o.assignedToId??null,plannedStartDate:asDate(o.plannedStartDate),plannedEndDate:asDate(o.plannedEndDate),...(o.plannedHours!==undefined?{plannedHours:o.plannedHours}:{}),notes:o.notes??null}))}},include});if(q.status==="ACCEPTED")await tx.quotation.update({where:{id:q.id},data:{status:"CONVERTED"}});return created;});res.status(201).json({success:true,message:"Production order created successfully",data});}catch(e){fail(res,e,"Unable to create production order");}};
export const updateProductionOrderController=async(req:AR,res:Response)=>{try{const v=updateProductionOrderSchema.safeParse(req.body);if(!v.success){res.status(400).json({success:false,message:"Please correct the production update fields",errors:v.error.flatten().fieldErrors});return;}const id=String(req.params.id),old=await prisma.productionOrder.findUnique({where:{id}});if(!old){res.status(404).json({success:false,message:"Production order was not found"});return;}const d=v.data,now=new Date();const u:any={};if(d.status!==undefined)u.status=d.status;if(d.priority!==undefined)u.priority=d.priority;if(d.progressPercent!==undefined)u.progressPercent=d.progressPercent;if(d.plannedStartDate!==undefined)u.plannedStartDate=asDate(d.plannedStartDate);if(d.plannedEndDate!==undefined)u.plannedEndDate=asDate(d.plannedEndDate);if(d.assignedToId!==undefined)u.assignedToId=d.assignedToId;if(d.notes!==undefined)u.notes=d.notes;if(d.status==="IN_PROGRESS"&&!old.actualStartDate)u.actualStartDate=now;if(d.status==="COMPLETED"){u.actualStartDate=old.actualStartDate??now;u.actualEndDate=now;u.progressPercent=100;}const data=await prisma.productionOrder.update({where:{id},data:u,include});res.json({success:true,data});}catch(e){fail(res,e,"Unable to update production order");}};
export const updateProductionOperationController=async(req:AR,res:Response)=>{try{const v=updateProductionOperationSchema.safeParse(req.body);if(!v.success){res.status(400).json({success:false,message:"Please correct the operation fields",errors:v.error.flatten().fieldErrors});return;}const id=String(req.params.operationId),old=await prisma.productionOperation.findUnique({where:{id}});if(!old||old.productionOrderId!==String(req.params.id)){res.status(404).json({success:false,message:"Production operation was not found"});return;}const d=v.data,now=new Date(),u:any={};for(const k of ["status","notes","workCenterId","machineId","assignedToId","plannedHours","actualHours","producedQuantity","rejectedQuantity","scrapQuantity","reworkQuantity","downtimeMinutes"] as const)if(d[k]!==undefined)u[k]=d[k];if(d.status==="IN_PROGRESS"&&!old.actualStartDate)u.actualStartDate=now;if(d.status==="COMPLETED"||d.status==="SKIPPED"){u.actualStartDate=old.actualStartDate??now;u.actualEndDate=now;}await prisma.$transaction(async tx=>{await tx.productionOperation.update({where:{id},data:u});await recalc(tx,old.productionOrderId);});const data=await prisma.productionOrder.findUnique({where:{id:old.productionOrderId},include});res.json({success:true,data});}catch(e){fail(res,e,"Unable to update production operation");}};

export const getProductionPlanningController=async(_req:Request,res:Response)=>{try{
 const [orders,centers,inventory]=await Promise.all([
  prisma.productionOrder.findMany({where:{status:{in:["PLANNED","RELEASED","IN_PROGRESS","ON_HOLD"]}},include:{operations:{include:{workCenterRef:true,machine:true}},materialMovements:{include:{inventoryItem:{select:{id:true,itemCode:true,name:true,unit:true,currentStock:true}}}}},orderBy:{plannedStartDate:"asc"}}),
  prisma.workCenter.findMany({include:{machines:true},orderBy:{name:"asc"}}),
  prisma.inventoryItem.findMany({where:{isActive:true},select:{id:true,itemCode:true,name:true,unit:true,currentStock:true,reorderLevel:true,unitCost:true,location:true,itemType:true},orderBy:{name:"asc"}})
 ]);
 const shortage=inventory.filter((x:any)=>Number(x.currentStock)<=Number(x.reorderLevel)).map((x:any)=>({...x,shortageQuantity:Math.max(Number(x.reorderLevel)-Number(x.currentStock),0)}));
 const capacity=centers.map((c:any)=>{const hours=orders.reduce((sum:number,o:any)=>sum+o.operations.filter((op:any)=>op.workCenterId===c.id).reduce((a:number,op:any)=>a+Number(op.plannedHours||0),0),0);return {...c,plannedHours:hours,availableHours:Number(c.capacityPerDay||0),utilizationPercent:Number(c.capacityPerDay||0)?Math.round(hours/Number(c.capacityPerDay)*100):0};});
 const stages={fabrication:0,assembly:0,testing:0,painting:0,packing:0,dispatch:0};
 for(const o of orders)for(const op of o.operations){const n=op.name.toLowerCase(); if(n.includes("fabric"))stages.fabrication++; else if(n.includes("assembl"))stages.assembly++; else if(n.includes("test"))stages.testing++; else if(n.includes("paint"))stages.painting++; else if(n.includes("pack"))stages.packing++; else if(n.includes("dispatch"))stages.dispatch++;}
 res.json({success:true,data:{orders,workCenters:capacity,shortages:shortage,stages,mrp:{openOrders:orders.length,materialShortages:shortage.length,plannedOperationHours:orders.reduce((s:number,o:any)=>s+o.operations.reduce((a:number,op:any)=>a+Number(op.plannedHours||0),0),0)}}});
 }catch(e){fail(res,e,"Unable to load production planning");}};

export const listWorkCentersController=async(_req:Request,res:Response)=>{try{res.json({success:true,data:await prisma.workCenter.findMany({include:{machines:true},orderBy:{name:"asc"}})});}catch(e){fail(res,e,"Unable to load work centers");}};
export const createWorkCenterController=async(req:AR,res:Response)=>{try{const v=createWorkCenterSchema.safeParse(req.body);if(!v.success){res.status(400).json({success:false,message:"Please correct work center fields"});return;}const d=v.data;res.status(201).json({success:true,data:await prisma.workCenter.create({data:{code:d.code,name:d.name,description:d.description??null,department:d.department??null,location:d.location??null,...(d.capacityPerDay!==undefined?{capacityPerDay:d.capacityPerDay}:{})}})});}catch(e){fail(res,e,"Unable to create work center");}};
export const createMachineController=async(req:AR,res:Response)=>{try{const v=createMachineSchema.safeParse(req.body);if(!v.success){res.status(400).json({success:false,message:"Please correct machine fields"});return;}const d=v.data;res.status(201).json({success:true,data:await prisma.productionMachine.create({data:{machineCode:d.machineCode,name:d.name,workCenterId:d.workCenterId,serialNumber:d.serialNumber??null,notes:d.notes??null}})});}catch(e){fail(res,e,"Unable to create machine");}};
export const createJobCardController=async(req:AR,res:Response)=>{try{const v=createJobCardSchema.safeParse(req.body);if(!v.success){res.status(400).json({success:false,message:"Please correct job card fields"});return;}const d=v.data,op=await prisma.productionOperation.findUnique({where:{id:d.operationId}});if(!op||op.productionOrderId!==d.productionOrderId){res.status(400).json({success:false,message:"Operation does not belong to this production order"});return;}const number=`JC-${new Date().getFullYear()}-${randomUUID().slice(0,8).toUpperCase()}`;const data=await prisma.productionJobCard.create({data:{jobCardNumber:number,productionOrderId:d.productionOrderId,operationId:d.operationId,assignedToId:d.assignedToId??null,plannedStartDate:asDate(d.plannedStartDate),plannedEndDate:asDate(d.plannedEndDate),...(d.plannedHours!==undefined?{plannedHours:d.plannedHours}:{}),notes:d.notes??null,createdById:req.auth?.userId??null}});res.status(201).json({success:true,data});}catch(e){fail(res,e,"Unable to create job card");}};
export const updateJobCardController=async(req:AR,res:Response)=>{try{const v=updateJobCardSchema.safeParse(req.body);if(!v.success){res.status(400).json({success:false,message:"Please correct job card fields",errors:v.error.flatten().fieldErrors});return;}const id=String(req.params.jobCardId),old=await prisma.productionJobCard.findUnique({where:{id}});if(!old){res.status(404).json({success:false,message:"Job card was not found"});return;}const d=v.data,now=new Date(),u:any={};if(d.status!==undefined)u.status=d.status;if(d.assignedToId!==undefined)u.assignedToId=d.assignedToId;for(const k of ["actualHours","producedQuantity","rejectedQuantity","scrapQuantity","reworkQuantity","downtimeMinutes","notes"] as const)if(d[k]!==undefined)u[k]=d[k];if(d.status==="IN_PROGRESS"&&!old.startedAt){u.startedAt=now;u.pausedAt=null;}if(d.status==="PAUSED")u.pausedAt=now;if(d.status==="COMPLETED"){u.startedAt=old.startedAt??now;u.completedAt=now;u.pausedAt=null;}const data=await prisma.productionJobCard.update({where:{id},data:u});if(d.status!==undefined||d.actualHours!==undefined||d.producedQuantity!==undefined||d.rejectedQuantity!==undefined||d.scrapQuantity!==undefined||d.reworkQuantity!==undefined||d.downtimeMinutes!==undefined){await prisma.productionOperation.update({where:{id:old.operationId},data:{...(d.status==="IN_PROGRESS"?{status:"IN_PROGRESS",actualStartDate:old.startedAt??now}:{}),...(d.status==="COMPLETED"?{status:"COMPLETED",actualEndDate:now,actualHours:d.actualHours??old.actualHours,producedQuantity:d.producedQuantity??old.producedQuantity,rejectedQuantity:d.rejectedQuantity??old.rejectedQuantity,scrapQuantity:d.scrapQuantity??old.scrapQuantity,reworkQuantity:d.reworkQuantity??old.reworkQuantity,downtimeMinutes:d.downtimeMinutes??old.downtimeMinutes}:{})}});await prisma.$transaction(async tx=>recalc(tx,old.productionOrderId));}res.json({success:true,data});}catch(e){fail(res,e,"Unable to update job card");}};

export const getShopFloorDashboardController=async(_req:Request,res:Response)=>{try{const [cards,orders,inspections,machines]=await Promise.all([
 prisma.productionJobCard.findMany({include:{operation:{select:{plannedHours:true,workCenterId:true,machineId:true,status:true}},assignedTo:{select:{id:true,employeeCode:true,firstName:true,lastName:true}}},orderBy:{updatedAt:"desc"}}),
 prisma.productionOrder.findMany({where:{status:{in:["PLANNED","RELEASED","IN_PROGRESS","ON_HOLD"]}},select:{id:true,status:true,title:true,productionNumber:true,plannedEndDate:true,quantity:true,producedQuantity:true,rejectedQuantity:true,scrapQuantity:true}}),
 prisma.qualityInspection.groupBy({by:["status"],_count:{_all:true}}),
 prisma.productionMachine.findMany({select:{id:true,status:true,workCenterId:true}})
]);
 const totalCards=cards.length,wip=cards.filter((c:any)=>["IN_PROGRESS","PAUSED"].includes(c.status)).length,delays=cards.filter((c:any)=>{const p=Number(c.plannedHours||c.operation?.plannedHours||0),a=Number(c.actualHours||0);return (p>0&&a>p&&c.status!=="COMPLETED")||(c.plannedEndDate&&new Date(c.plannedEndDate)<new Date()&&c.status!=="COMPLETED"&&c.status!=="CANCELLED")}).length;
 const planned=cards.reduce((s:number,c:any)=>s+Number(c.plannedHours||c.operation?.plannedHours||0),0),actual=cards.reduce((s:number,c:any)=>s+Number(c.actualHours||0),0),downtime=cards.reduce((s:number,c:any)=>s+Number(c.downtimeMinutes||0),0),produced=cards.reduce((s:number,c:any)=>s+Number(c.producedQuantity||0),0),rejects=cards.reduce((s:number,c:any)=>s+Number(c.rejectedQuantity||0)+Number(c.scrapQuantity||0),0);
 const availability=actual+downtime/60>0?Math.min(100,actual/(actual+downtime/60)*100):0,performance=actual>0?Math.min(100,planned/actual*100):0,quality=produced+rejects>0?Math.max(0,produced/(produced+rejects)*100):0,oee=availability*performance*quality/10000,efficiency=actual>0?Math.min(100,planned/actual*100):0,rejectionPercent=produced+rejects>0?rejects/(produced+rejects)*100:0;
 const machineActive=machines.filter((m:any)=>m.status==="IN_USE").length, machineCapacity=Math.max(machines.length*8,8),machineUtilization=Math.min(100,actual/machineCapacity*100);
 const q={total:inspections.reduce((s:any,x:any)=>s+x._count._all,0),passed:inspections.find((x:any)=>x.status==="PASSED")?._count._all||0,failed:inspections.find((x:any)=>x.status==="FAILED")?._count._all||0,pending:inspections.filter((x:any)=>["PENDING","IN_PROGRESS","ON_HOLD"].includes(x.status)).reduce((s:any,x:any)=>s+x._count._all,0)};
 res.json({success:true,data:{cards:cards.slice(0,100),metrics:{totalCards,wip,delays,plannedHours:planned,actualHours:actual,downtimeMinutes:downtime,produced,rejects,efficiency,rejectionPercent,oee,availability,performance,quality,machineUtilization,machineActive,machineTotal:machines.length},quality:q,orders}});
 }catch(e){fail(res,e,"Unable to load shop floor dashboard");}};

export const listProductionInventoryController=async(_req:Request,res:Response)=>{try{const data=await prisma.inventoryItem.findMany({select:{id:true,itemCode:true,name:true,unit:true,currentStock:true},orderBy:{name:"asc"}});res.json({success:true,data});}catch(e){fail(res,e,"Unable to load production inventory");}};
export const recordMaterialMovementController=async(req:AR,res:Response)=>{try{const v=materialMovementSchema.safeParse(req.body);if(!v.success){res.status(400).json({success:false,message:"Please correct material fields",errors:v.error.flatten().fieldErrors});return;}const orderId=String(req.params.id),d=v.data;const order=await prisma.productionOrder.findUnique({where:{id:orderId},select:{id:true}});if(!order){res.status(404).json({success:false,message:"Production order was not found"});return;}const item=await prisma.inventoryItem.findUnique({where:{id:d.inventoryItemId}});if(!item){res.status(404).json({success:false,message:"Inventory item was not found"});return;}const qty=Number(d.quantity),isOut=["ISSUE","CONSUMPTION","SCRAP"].includes(d.movementType);if(isOut&&Number(item.currentStock)<qty){res.status(400).json({success:false,message:`Insufficient stock. Available: ${item.currentStock.toString()} ${item.unit}`});return;}const data=await prisma.$transaction(async tx=>{const balance=Number(item.currentStock)+(isOut?-qty:qty);const move=await tx.productionMaterialConsumption.create({data:{productionOrderId:orderId,inventoryItemId:item.id,movementType:d.movementType,quantity:d.quantity,unitCost:item.unitCost,heatNumber:d.heatNumber??null,batchNumber:d.batchNumber??null,serialNumber:d.serialNumber??null,materialCertificateNumber:d.materialCertificateNumber??null,notes:d.notes??null,recordedById:req.auth?.userId??null}});await tx.inventoryItem.update({where:{id:item.id},data:{currentStock:balance}});await tx.stockMovement.create({data:{inventoryItemId:item.id,movementType:isOut?"ISSUE":"RETURN_IN",quantity:d.quantity,balanceAfter:balance,unitCost:item.unitCost,referenceType:"PRODUCTION",referenceNumber:orderId,notes:d.notes??null,createdById:req.auth?.userId??null}});return move;});res.status(201).json({success:true,data});}catch(e){fail(res,e,"Unable to record material movement");}};
export const createTraceabilityController=async(req:AR,res:Response)=>{try{const v=traceabilitySchema.safeParse(req.body);if(!v.success){res.status(400).json({success:false,message:"Please correct traceability fields",errors:v.error.flatten().fieldErrors});return;}const d=v.data,productionOrderId=String(req.params.id);const data=await prisma.productionTraceability.create({data:{productionOrderId,operationId:d.operationId??null,inventoryItemId:d.inventoryItemId??null,componentName:d.componentName,heatNumber:d.heatNumber??null,batchNumber:d.batchNumber??null,serialNumber:d.serialNumber??null,materialCertificateNumber:d.materialCertificateNumber??null,quantity:d.quantity,unit:d.unit,notes:d.notes??null}});res.status(201).json({success:true,data});}catch(e){fail(res,e,"Unable to create traceability record");}};
export const createDowntimeController=async(req:AR,res:Response)=>{try{const v=downtimeSchema.safeParse(req.body);if(!v.success){res.status(400).json({success:false,message:"Please correct downtime fields",errors:v.error.flatten().fieldErrors});return;}const d=v.data,productionOrderId=String(req.params.id),start=new Date(d.startedAt),end=new Date(d.endedAt),durationMinutes=Math.max(1,Math.round((end.getTime()-start.getTime())/60000));const data=await prisma.$transaction(async tx=>{const rec=await tx.productionDowntime.create({data:{productionOrderId,operationId:d.operationId??null,machineId:d.machineId??null,category:d.category,reason:d.reason,startedAt:start,endedAt:end,durationMinutes,notes:d.notes??null}});if(d.operationId)await tx.productionOperation.update({where:{id:d.operationId},data:{downtimeMinutes:{increment:durationMinutes}}});return rec;});res.status(201).json({success:true,data});}catch(e){fail(res,e,"Unable to record downtime");}};
