import { randomUUID } from "node:crypto";
import type { Request, Response } from "express";
import type { Prisma } from "../generated/prisma/client.js";
import { prisma } from "../config/database.js";
import { createCostLineSchema,createMilestoneSchema,createProjectSchema,createTaskSchema,updateMilestoneSchema,updateProjectSchema,updateTaskSchema } from "../utils/project-validation.js";
type AR=Request&{auth?:{userId:string}};
const code=(p:string)=>`${p}-${new Date().getFullYear()}-${randomUUID().slice(0,8).toUpperCase()}`;
const bad=(res:Response,v:any)=>res.status(400).json({success:false,message:"Please correct the fields",errors:v.error.flatten().fieldErrors});
const include={customer:true,salesOrder:true,manager:{select:{id:true,firstName:true,lastName:true,email:true}},milestones:{orderBy:{sequence:"asc" as const},include:{tasks:true}},tasks:{include:{assignedTo:{select:{id:true,firstName:true,lastName:true}}},orderBy:{createdAt:"desc" as const}},costLines:{orderBy:{incurredOn:"desc" as const}}} as const;
async function audit(r:AR,action:string,entity:string,id:string,values?:Prisma.InputJsonValue){await prisma.auditLog.create({data:{userId:r.auth?.userId??null,action,entity,entityId:id,ipAddress:r.ip??null,...(values!==undefined?{newValues:values}:{})}});}
async function recalc(projectId:string){
 const ms=await prisma.projectMilestone.findMany({where:{projectId},select:{progressPercent:true}});
 const progress=ms.length?ms.reduce((a,m)=>a+Number(m.progressPercent),0)/ms.length:0;
 await prisma.project.update({where:{id:projectId},data:{progressPercent:progress}});
}
export const eligibleOrders=async(_r:Request,res:Response)=>{const rows=await prisma.salesOrder.findMany({where:{status:{in:["CONFIRMED","ADVANCE_PENDING","ADVANCE_RECEIVED","IN_PRODUCTION","READY_FOR_DISPATCH","DISPATCHED","INSTALLED","COMMISSIONED","CLOSED"]},project:null},include:{customer:true},orderBy:{createdAt:"desc"}});res.json({success:true,data:rows});};
export const listProjects=async(_r:Request,res:Response)=>res.json({success:true,data:await prisma.project.findMany({include,orderBy:{createdAt:"desc"}})});
export const getProject=async(r:Request,res:Response)=>{const row=await prisma.project.findUnique({where:{id:String(r.params.id)},include});if(!row){res.status(404).json({success:false,message:"Project not found"});return;}res.json({success:true,data:row});};
export const createProject=async(r:AR,res:Response)=>{const v=createProjectSchema.safeParse(r.body);if(!v.success){bad(res,v);return;}const d=v.data;const so=await prisma.salesOrder.findUnique({where:{id:d.salesOrderId}});if(!so){res.status(404).json({success:false,message:"Sales order not found"});return;}if(!["CONFIRMED","ADVANCE_PENDING","ADVANCE_RECEIVED","IN_PRODUCTION","READY_FOR_DISPATCH","DISPATCHED","INSTALLED","COMMISSIONED","CLOSED"].includes(so.status)){res.status(400).json({success:false,message:"Sales order must be confirmed before creating a project"});return;}if(await prisma.project.findUnique({where:{salesOrderId:so.id}})){res.status(409).json({success:false,message:"A project already exists for this sales order"});return;}const s=await prisma.companySettings.findUnique({where:{id:"company"}});const row=await prisma.project.create({data:{projectNumber:code(s?.projectPrefix??"PRJ"),salesOrderId:so.id,customerId:so.customerId,title:d.title,priority:d.priority,budgetAmount:so.totalAmount,revenueAmount:so.totalAmount,createdById:r.auth?.userId??null,...(d.description?{description:d.description}:{}),...(d.plannedStartDate?{plannedStartDate:d.plannedStartDate}:{}),...(d.plannedEndDate?{plannedEndDate:d.plannedEndDate}:{}),...(d.managerId?{managerId:d.managerId}:{}),...(d.notes?{notes:d.notes}:{})},include});
const defaults=["Drawing Approval Milestone","Material Procurement Milestone","Fabrication Completion","Hydro Test Milestone","Dispatch Milestone","Installation Milestone","Commissioning Milestone"];
for(let i=0;i<defaults.length;i++) await prisma.projectMilestone.create({data:{projectId:row.id,sequence:i+1,name:defaults[i]!}});
const fresh=await prisma.project.findUnique({where:{id:row.id},include});await audit(r,"CREATE","Project",row.id,{projectNumber:row.projectNumber});res.status(201).json({success:true,message:"Project created successfully",data:fresh});};
export const updateProject=async(r:AR,res:Response)=>{const v=updateProjectSchema.safeParse(r.body);if(!v.success){bad(res,v);return;}const id=String(r.params.id);const old=await prisma.project.findUnique({where:{id}});if(!old){res.status(404).json({success:false,message:"Project not found"});return;}const data:any={...v.data};if(v.data.status==="ACTIVE"&&!old.actualStartDate)data.actualStartDate=new Date();if(v.data.status==="COMPLETED"){data.actualEndDate=new Date();data.progressPercent=100;}const row=await prisma.project.update({where:{id},data,include});await audit(r,"UPDATE","Project",id,{status:row.status});res.json({success:true,message:"Project updated successfully",data:row});};
export const createMilestone=async(r:AR,res:Response)=>{const v=createMilestoneSchema.safeParse(r.body);if(!v.success){bad(res,v);return;}const d=v.data;const last=await prisma.projectMilestone.aggregate({where:{projectId:d.projectId},_max:{sequence:true}});const row=await prisma.projectMilestone.create({data:{projectId:d.projectId,sequence:(last._max.sequence??0)+1,name:d.name,...(d.description?{description:d.description}:{}),...(d.plannedDate?{plannedDate:d.plannedDate}:{}),...(d.notes?{notes:d.notes}:{})}});await recalc(d.projectId);await audit(r,"CREATE","ProjectMilestone",row.id,{name:row.name});res.status(201).json({success:true,message:"Milestone created successfully",data:row});};
export const updateMilestone=async(r:AR,res:Response)=>{const v=updateMilestoneSchema.safeParse(r.body);if(!v.success){bad(res,v);return;}const id=String(r.params.id);const old=await prisma.projectMilestone.findUnique({where:{id}});if(!old){res.status(404).json({success:false,message:"Milestone not found"});return;}const data:any={...v.data};if(v.data.status==="COMPLETED"){data.completedAt=new Date();data.progressPercent=100;}const row=await prisma.projectMilestone.update({where:{id},data});await recalc(row.projectId);await audit(r,"UPDATE","ProjectMilestone",id,{status:row.status});res.json({success:true,message:"Milestone updated successfully",data:row});};
export const createTask=async(r:AR,res:Response)=>{const v=createTaskSchema.safeParse(r.body);if(!v.success){bad(res,v);return;}const d=v.data;const row=await prisma.projectTask.create({data:{projectId:d.projectId,title:d.title,priority:d.priority,createdById:r.auth?.userId??null,...(d.milestoneId?{milestoneId:d.milestoneId}:{}),...(d.description?{description:d.description}:{}),...(d.department?{department:d.department}:{}),...(d.plannedDate?{plannedDate:d.plannedDate}:{}),...(d.dueDate?{dueDate:d.dueDate}:{}),...(d.assignedToId?{assignedToId:d.assignedToId}:{}),...(d.notes?{notes:d.notes}:{})}});await audit(r,"CREATE","ProjectTask",row.id,{title:row.title});res.status(201).json({success:true,message:"Task created successfully",data:row});};
export const updateTask=async(r:AR,res:Response)=>{const v=updateTaskSchema.safeParse(r.body);if(!v.success){bad(res,v);return;}const id=String(r.params.id);const old=await prisma.projectTask.findUnique({where:{id}});if(!old){res.status(404).json({success:false,message:"Task not found"});return;}const data:any={...v.data};if(v.data.status==="COMPLETED")data.completedAt=new Date();const row=await prisma.projectTask.update({where:{id},data});await audit(r,"UPDATE","ProjectTask",id,{status:row.status});res.json({success:true,message:"Task updated successfully",data:row});};

export const createCostLine=async(r:AR,res:Response)=>{const v=createCostLineSchema.safeParse(r.body);if(!v.success){bad(res,v);return;}const d=v.data;const project=await prisma.project.findUnique({where:{id:d.projectId}});if(!project){res.status(404).json({success:false,message:"Project not found"});return;}const row=await prisma.projectCostLine.create({data:{projectId:d.projectId,category:d.category,description:d.description,plannedCost:d.plannedCost,actualCost:d.actualCost,...(d.incurredOn?{incurredOn:d.incurredOn}:{})}});const agg=await prisma.projectCostLine.aggregate({where:{projectId:d.projectId},_sum:{actualCost:true}});await prisma.project.update({where:{id:d.projectId},data:{actualCost:agg._sum.actualCost??0}});await audit(r,"CREATE","ProjectCostLine",row.id,{category:row.category,actualCost:row.actualCost});res.status(201).json({success:true,message:"Project cost added",data:row});};
export const getProjectSummary=async(r:Request,res:Response)=>{const id=String(r.params.id);const p=await prisma.project.findUnique({where:{id},include:{costLines:true,milestones:true}});if(!p){res.status(404).json({success:false,message:"Project not found"});return;}const today=new Date();const plannedEnd=p.plannedEndDate?new Date(p.plannedEndDate):null;const actualEnd=p.actualEndDate?new Date(p.actualEndDate):null;const end=actualEnd??today;const delayDays=plannedEnd&&end>plannedEnd?Math.ceil((end.getTime()-plannedEnd.getTime())/86400000):0;const profit=Number(p.revenueAmount)-Number(p.actualCost);const plannedCost=p.costLines.reduce((a,c)=>a+Number(c.plannedCost),0);res.json({success:true,data:{projectId:p.id,stage:p.stage,budgetAmount:p.budgetAmount,revenueAmount:p.revenueAmount,actualCost:p.actualCost,plannedCost,profit,profitMargin:Number(p.revenueAmount)?profit/Number(p.revenueAmount)*100:0,progressPercent:p.progressPercent,delayDays,plannedStartDate:p.plannedStartDate,plannedEndDate:p.plannedEndDate,actualStartDate:p.actualStartDate,actualEndDate:p.actualEndDate,milestones:p.milestones}});};
