import { Router } from "express";
import { authenticate } from "../middleware/auth.middleware.js";
import * as c from "../controllers/finance.controller.js";
export const financeRouter=Router(); financeRouter.use(authenticate);
financeRouter.get("/dashboard",c.dashboard);
financeRouter.get("/accounts",c.listAccounts); financeRouter.post("/accounts",c.createAccount);
financeRouter.get("/journals",c.listJournals); financeRouter.post("/journals",c.createJournal); financeRouter.post("/journals/:id/post",c.postJournal);
financeRouter.get("/receivables",c.receivables);
financeRouter.get("/eligible-grns",c.eligibleGrns);
financeRouter.get("/vendor-bills",c.listBills); financeRouter.post("/vendor-bills",c.createBill);
financeRouter.post("/vendor-payments",c.createVendorPayment);
financeRouter.get("/expenses",c.listExpenses); financeRouter.post("/expenses",c.createExpense); financeRouter.patch("/expenses/:id",c.updateExpense);
financeRouter.get("/gst-summary",c.gstSummary);
financeRouter.get("/reports/trial-balance",c.trialBalance); financeRouter.get("/reports/profit-loss",c.profitLoss); financeRouter.get("/reports/balance-sheet",c.balanceSheet);
financeRouter.post("/receipts",c.createCustomerReceipt);
financeRouter.get("/receipts",c.listReceipts);
financeRouter.post("/payment-followups",c.createPaymentFollowUp);
financeRouter.get("/payment-followups",c.listPaymentFollowUps);
financeRouter.get("/vendor-payment-approvals",c.listVendorPaymentApprovals);
financeRouter.patch("/vendor-payment-approvals/:id",c.approveVendorPayment);
financeRouter.get("/reports/cash-flow",c.cashFlow);
financeRouter.get("/reports/customer-profitability",c.customerProfitability);
financeRouter.get("/reports/product-profitability",c.productProfitability);
financeRouter.get("/reports/project-profitability",c.projectProfitability);
financeRouter.get("/revenue-recognition",c.revenueRecognitions);
financeRouter.post("/revenue-recognition",c.createRevenueRecognition);
financeRouter.get("/tds-summary",c.tdsSummary);
financeRouter.post("/tds",c.createTds);
financeRouter.post("/product-costs",c.createProductCost);
