import {useEffect,useState} from "react";import type {ReactNode} from "react";
import {RefreshCw,CheckCircle2,AlertCircle,Plus} from "lucide-react";
import * as api from "../services/finance.service";
import type {PaymentMethod,Receivable} from "../types/finance";
import "./FinancePage.css";
const money=(v:any)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(v||0));
export default function FinanceModule15(){
 const [ar,setAr]=useState<Receivable[]>([]),[receipts,setReceipts]=useState<any[]>([]),[follow,setFollow]=useState<any[]>([]),[approvals,setApprovals]=useState<any[]>([]),[cf,setCf]=useState<any>(null),[cust,setCust]=useState<any[]>([]),[prod,setProd]=useState<any[]>([]),[proj,setProj]=useState<any[]>([]),[rev,setRev]=useState<any[]>([]),[tds,setTds]=useState<any[]>([]),[tab,setTab]=useState("receipts"),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 const load=async()=>{try{setErr("");const [a,r,f,v,c,cu,pr,pj,rr,t]=await Promise.all([api.getReceivables(),api.getReceipts(),api.getPaymentFollowUps(),api.getVendorPaymentApprovals(),api.getCashFlow(),api.getCustomerProfitability(),api.getProductProfitability(),api.getProjectProfitability(),api.getRevenueRecognitions(),api.getTdsSummary()]);setAr(a);setReceipts(r);setFollow(f);setApprovals(v);setCf(c);setCust(cu);setProd(pr);setProj(pj);setRev(rr);setTds(t)}catch(e){setErr(e instanceof Error?e.message:"Unable to load Module 15")}};
 useEffect(()=>{void load()},[]);
 const tabs=["receipts","followups","approvals","cashflow","profitability","revenue","gst-tds"];
 return <section className="finance-card" style={{marginTop:18}}><div className="finance-toolbar"><div><b>Module 15 — Finance</b><div style={{fontSize:13,opacity:.7}}>AR, AP, receipts, approvals, GST/TDS, profitability and revenue recognition</div></div><button className="finance-secondary" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button></div>{err&&<div className="finance-alert error"><AlertCircle size={17}/>{err}</div>}{msg&&<div className="finance-alert success"><CheckCircle2 size={17}/>{msg}</div>}<div className="finance-tabs">{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x.replaceAll("-"," & ").replace("gst & tds","GST / TDS")}</button>)}</div>
 {tab==="receipts"&&<Receipts ar={ar} receipts={receipts} onDone={async()=>{setMsg("Receipt recorded.");await load()}}/>}
 {tab==="followups"&&<Followups rows={follow} ar={ar} onDone={async()=>{setMsg("Payment follow-up saved.");await load()}}/>}
 {tab==="approvals"&&<Approvals rows={approvals} onDone={async()=>{setMsg("Payment approval updated.");await load()}}/>}
 {tab==="cashflow"&&<div className="finance-report-summary"><article><span>Cash Inflow</span><strong>{money(cf?.inflow)}</strong></article><article><span>Cash Outflow</span><strong>{money(cf?.outflow)}</strong></article><article><span>Net Cash Flow</span><strong>{money(cf?.netCashFlow)}</strong></article><article><span>Customer Receipts</span><strong>{money(cf?.customerReceipts)}</strong></article><article><span>Vendor Payments</span><strong>{money(cf?.vendorPayments)}</strong></article></div>}
 {tab==="profitability"&&<div className="finance-table-wrap"><h3>Customer Profitability</h3><MiniTable rows={cust} cols={["companyName","revenue","cost","profit"]}/><h3>Project Profitability</h3><MiniTable rows={proj} cols={["projectNumber","title","revenue","cost","profit"]}/><h3>Product Profitability</h3><ProductCostForm onDone={async()=>{setMsg("Product standard cost saved.");await load()}}/><MiniTable rows={prod} cols={["productName","quantity","revenue","cost","profit"]}/></div>}
 {tab==="revenue"&&<Revenue rows={rev} onDone={async()=>{setMsg("Revenue recognition saved.");await load()}}/>}
 {tab==="gst-tds"&&<Tax rows={tds} onDone={async()=>{setMsg("TDS record saved.");await load()}}/>}
 </section>
}
function Receipts({ar,receipts,onDone}:{ar:Receivable[];receipts:any[];onDone:()=>Promise<void>}){const [invoiceId,setInvoiceId]=useState(""),[amount,setAmount]=useState(""),[method,setMethod]=useState<PaymentMethod>("BANK_TRANSFER"),[ref,setRef]=useState("");const submit=async()=>{if(!invoiceId||!amount)return;await api.createCustomerReceipt({invoiceId,amount:Number(amount),method,referenceNumber:ref||undefined});setInvoiceId("");setAmount("");setRef("");await onDone()};return <><div className="finance-form-row"><select value={invoiceId} onChange={e=>setInvoiceId(e.target.value)}><option value="">Select invoice</option>{ar.filter(x=>Number(x.balanceAmount)>0).map(x=><option key={x.id} value={x.id}>{x.invoiceNumber} · {x.customer.companyName} · {money(x.balanceAmount)}</option>)}</select><input type="number" min=".01" step=".01" placeholder="Receipt amount" value={amount} onChange={e=>setAmount(e.target.value)}/><select value={method} onChange={e=>setMethod(e.target.value as PaymentMethod)}>{["CASH","BANK_TRANSFER","UPI","CHEQUE","CARD","OTHER"].map(x=><option key={x}>{x}</option>)}</select><input placeholder="Reference" value={ref} onChange={e=>setRef(e.target.value)}/><button className="finance-primary" onClick={submit}><Plus size={16}/>Receipt</button></div><MiniTable rows={receipts} cols={["receiptNumber","invoiceNumber","customerName","amount","method","receiptDate"]}/></>}
function Followups({rows,ar,onDone}:{rows:any[];ar:Receivable[];onDone:()=>Promise<void>}){const [invoiceId,setInvoiceId]=useState(""),[next,setNext]=useState(""),[notes,setNotes]=useState("");const submit=async()=>{if(!invoiceId)return;await api.createPaymentFollowUp({invoiceId,nextFollowUpDate:next?new Date(next).toISOString():undefined,notes});setNotes("");await onDone()};return <><div className="finance-form-row"><select value={invoiceId} onChange={e=>setInvoiceId(e.target.value)}><option value="">Select invoice</option>{ar.filter(x=>Number(x.balanceAmount)>0).map(x=><option key={x.id} value={x.id}>{x.invoiceNumber} · {x.customer.companyName}</option>)}</select><input type="date" value={next} onChange={e=>setNext(e.target.value)}/><input placeholder="Follow-up note" value={notes} onChange={e=>setNotes(e.target.value)}/><button className="finance-primary" onClick={submit}>Save Follow-up</button></div><MiniTable rows={rows} cols={["invoiceNumber","customerName","status","nextFollowUpDate","notes"]}/></>}
function Approvals({rows,onDone}:{rows:any[];onDone:()=>Promise<void>}){return <MiniTable rows={rows} cols={["paymentNumber","billNumber","vendorName","amount","status"]} actions={(x)=>x.status==="PENDING"?<><button className="finance-mini" onClick={async()=>{await api.approveVendorPayment(x.id,"APPROVED");await onDone()}}>Approve</button><button className="finance-mini" onClick={async()=>{await api.approveVendorPayment(x.id,"REJECTED","Finance review rejected");await onDone()}}>Reject</button></>:null}/>}
function Revenue({rows,onDone}:{rows:any[];onDone:()=>Promise<void>}){const [type,setType]=useState("MILESTONE"),[projectId,setProjectId]=useState(""),[amount,setAmount]=useState(""),[percentage,setPercentage]=useState("");const submit=async()=>{if(!amount&&type!=="PERCENTAGE_COMPLETION")return;await api.createRevenueRecognition({recognitionType:type,projectId:projectId||undefined,amount:Number(amount||0),percentage:percentage?Number(percentage):undefined});setAmount("");setPercentage("");await onDone()};return <><div className="finance-form-row"><select value={type} onChange={e=>setType(e.target.value)}>{["MILESTONE","PERCENTAGE_COMPLETION","DISPATCH","COMMISSIONING"].map(x=><option key={x}>{x}</option>)}</select><input placeholder="Project ID (optional)" value={projectId} onChange={e=>setProjectId(e.target.value)}/><input type="number" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/>{type==="PERCENTAGE_COMPLETION"&&<input type="number" placeholder="Completion %" value={percentage} onChange={e=>setPercentage(e.target.value)}/>}<button className="finance-primary" onClick={submit}>Recognize Revenue</button></div><MiniTable rows={rows} cols={["recognitionNumber","recognitionType","projectNumber","percentage","amount","recognitionDate"]}/></>}
function Tax({rows,onDone}:{rows:any[];onDone:()=>Promise<void>}){const [partyType,setPartyType]=useState("VENDOR"),[partyId,setPartyId]=useState(""),[section,setSection]=useState("194C"),[rate,setRate]=useState("1"),[taxable,setTaxable]=useState("");const submit=async()=>{if(!partyId||!taxable)return;await api.createTds({partyType,partyId,documentType:"FINANCE",documentId:"MANUAL",tdsSection:section,rate:Number(rate),taxableAmount:Number(taxable)});setTaxable("");await onDone()};return <><div className="finance-form-row"><input placeholder="Customer/Vendor ID" value={partyId} onChange={e=>setPartyId(e.target.value)}/><select value={partyType} onChange={e=>setPartyType(e.target.value)}><option>CUSTOMER</option><option>VENDOR</option></select><input value={section} onChange={e=>setSection(e.target.value)} placeholder="TDS section"/><input type="number" value={rate} onChange={e=>setRate(e.target.value)} placeholder="Rate %"/><input type="number" value={taxable} onChange={e=>setTaxable(e.target.value)} placeholder="Taxable amount"/><button className="finance-primary" onClick={submit}>Add TDS</button></div><MiniTable rows={rows} cols={["partyType","tdsSection","status","taxableAmount","tdsAmount","records"]}/></>}
function MiniTable({rows,cols,actions}:{rows:any[];cols:string[];actions?:(x:any)=>ReactNode}){if(!rows.length)return <div className="finance-empty">No records found.</div>;return <div className="finance-table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll(/([A-Z])/g," $1")}</th>)}{actions&&<th>Actions</th>}</tr></thead><tbody>{rows.map((x,i)=><tr key={x.id||i}>{cols.map(c=><td key={c}>{typeof x[c]==="number"||/[Aa]mount|revenue|cost|profit|quantity|percentage/.test(c)?money(x[c]):String(x[c]??"—")}</td>)}{actions&&<td>{actions(x)}</td>}</tr>)}</tbody></table></div>}

function ProductCostForm({onDone}:{onDone:()=>Promise<void>}){const [name,setName]=useState(""),[cost,setCost]=useState("");const save=async()=>{if(!name)return;await api.createProductCost({productName:name,standardCost:Number(cost||0)});setName("");setCost("");await onDone()};return <div className="finance-form-row"><input placeholder="Product / service name" value={name} onChange={e=>setName(e.target.value)}/><input type="number" min="0" placeholder="Standard cost / unit" value={cost} onChange={e=>setCost(e.target.value)}/><button className="finance-primary" onClick={save}>Save Product Cost</button></div>}
