import {useEffect,useState} from "react";
import * as api from "../services/hr.service";
import type {Employee} from "../types/hr";
const field=(label:string,key:string,value:any,setter:any,type="text")=><label className="hr-field"><span>{label}</span><input type={type} value={value??""} onChange={e=>setter((x:any)=>({...x,[key]:e.target.value}))}/></label>;
export default function HrModule16Panel({employees,onDone}:{employees:Employee[];onDone?:()=>void}){
 const [tab,setTab]=useState("recruitment"),[rows,setRows]=useState<any[]>([]),[f,setF]=useState<any>({}),[msg,setMsg]=useState("");
 const load=async()=>{try{const d=tab==="recruitment"?await api.getRecruitments():tab==="shifts"?await api.getShifts():tab==="overtime"?await api.getOvertime():tab==="biometric"?await api.getBiometric():tab==="appraisals"?await api.getAppraisals():tab==="skills"?await api.getSkills():tab==="certifications"?await api.getCertifications():tab==="training"?await api.getTraining():await api.getPayslips();setRows(d as any[])}catch(e){setMsg(e instanceof Error?e.message:"Unable to load")}};
 useEffect(()=>{void load();setF({});},[tab]);
 const save=async()=>{try{if(tab==="recruitment")await api.createRecruitment(f);if(tab==="shifts")await api.createShift(f);if(tab==="overtime")await api.createOvertime(f);if(tab==="biometric")await api.recordBiometric(f);if(tab==="appraisals")await api.createAppraisal(f);if(tab==="skills")await api.createSkill(f);if(tab==="certifications")await api.createCertification(f);if(tab==="training")await api.createTraining(f);if(tab==="payslips")await api.generatePayslip(f);setMsg("Saved successfully");setF({});await load();onDone?.()}catch(e){setMsg(e instanceof Error?e.message:"Unable to save")}};
 const tabs=["recruitment","shifts","overtime","biometric","appraisals","skills","certifications","training","payslips"];
 return <section className="hr-card" style={{marginTop:16}}><div className="hr-toolbar"><div className="hr-tabs">{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x.replace("biometric","Biometric").replace("payslips","Payslips")}</button>)}</div></div>{msg&&<div className="hr-alert success">{msg}</div>}<div style={{padding:18}}>
 <div className="hr-grid" style={{marginBottom:14}}>{tab==="recruitment"&&<>{field("Job title","jobTitle",f.jobTitle,setF)}{field("Positions","positions",f.positions,setF,"number")}{field("Description","description",f.description,setF)}</>}
 {tab==="shifts"&&<>{field("Code","code",f.code,setF)}{field("Name","name",f.name,setF)}{field("Start","startTime",f.startTime,setF,"time")}{field("End","endTime",f.endTime,setF,"time")}</>}
 {tab==="overtime"&&<><select className="hr-field" value={f.employeeId||""} onChange={e=>setF((x:any)=>({...x,employeeId:e.target.value}))}><option value="">Employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employeeCode} - {e.firstName} {e.lastName}</option>)}</select>{field("Date","date",f.date,setF,"date")}{field("Hours","hours",f.hours,setF,"number")}{field("Rate","rate",f.rate,setF,"number")}</>}
 {tab==="biometric"&&<><select className="hr-field" value={f.employeeId||""} onChange={e=>setF((x:any)=>({...x,employeeId:e.target.value}))}><option value="">Employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employeeCode}</option>)}</select><select className="hr-field" value={f.eventType||"CHECK_IN"} onChange={e=>setF((x:any)=>({...x,eventType:e.target.value}))}><option>CHECK_IN</option><option>CHECK_OUT</option><option>BREAK_IN</option><option>BREAK_OUT</option></select>{field("Event time","eventAt",f.eventAt,setF,"datetime-local")}</>}
 {tab==="appraisals"&&<><select className="hr-field" value={f.employeeId||""} onChange={e=>setF((x:any)=>({...x,employeeId:e.target.value}))}><option value="">Employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employeeCode}</option>)}</select>{field("Period","appraisalPeriod",f.appraisalPeriod,setF)}{field("Rating","rating",f.rating,setF,"number")}{field("Comments","comments",f.comments,setF)}</>}
 {tab==="skills"&&<>{field("Skill code","skillCode",f.skillCode,setF)}{field("Skill name","name",f.name,setF)}{field("Category","category",f.category,setF)}</>}
 {tab==="certifications"&&<><select className="hr-field" value={f.employeeId||""} onChange={e=>setF((x:any)=>({...x,employeeId:e.target.value}))}><option value="">Employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employeeCode}</option>)}</select><select className="hr-field" value={f.certificationType||"WELDER"} onChange={e=>setF((x:any)=>({...x,certificationType:e.target.value}))}><option>WELDER</option><option>OPERATOR</option><option>OTHER</option></select>{field("Certification","certificationName",f.certificationName,setF)}{field("Expiry","expiryDate",f.expiryDate,setF,"date")}</>}
 {tab==="training"&&<>{field("Title","title",f.title,setF)}{field("Trainer","trainer",f.trainer,setF)}{field("Provider","provider",f.provider,setF)}{field("Start date","startDate",f.startDate,setF,"date")}</>}
 {tab==="payslips"&&<>{field("Payroll item ID","payrollItemId",f.payrollItemId,setF)}</>}
 </div><button className="hr-primary" onClick={save}>Save {tab}</button>
 <div className="hr-table-wrap" style={{marginTop:18}}><table><thead><tr>{rows.length?Object.keys(rows[0]).slice(0,8).map(k=><th key={k}>{k}</th>):<th>No records</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{Object.keys(r).slice(0,8).map(k=><td key={k}>{String(r[k]??"—")}</td>)}</tr>)}</tbody></table></div>
 </div></section>
}
