import {useCallback,useEffect,useState} from "react";
import {Activity,AlertTriangle,Factory,Plus,RefreshCw,Search,Wifi,WifiOff,X} from "lucide-react";
import {addSensorReading,createIotAlert,createIotDevice,getIotDevices,getManagementDashboard,updateIotAlert,updateIotDevice} from "../services/iot.service";
import type {IotDevice,ManagementDashboard,IotDeviceStatus} from "../types/iot";
import "./IotDashboardPage.css";

export default function IotDashboardPage(){
 const[data,setData]=useState<ManagementDashboard|null>(null),[devices,setDevices]=useState<IotDevice[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState("");
 const[show,setShow]=useState(false),[selected,setSelected]=useState<IotDevice|null>(null),[code,setCode]=useState(""),[name,setName]=useState(""),[type,setType]=useState("Industrial Sensor"),[location,setLocation]=useState("");
 const[sensor,setSensor]=useState("Temperature"),[value,setValue]=useState(""),[unit,setUnit]=useState("°C"),[alertTitle,setAlertTitle]=useState("");
 const load=useCallback(async(q="")=>{try{setLoading(true);setError("");const[d,v]=await Promise.all([getManagementDashboard(),getIotDevices(q)]);setData(d);setDevices(v)}catch(e){setError(e instanceof Error?e.message:"Unable to load IoT dashboard")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function create(e:React.FormEvent){e.preventDefault();try{await createIotDevice({deviceCode:code,name,deviceType:type,...(location?{location}:{})});setShow(false);setCode("");setName("");setLocation("");await load(search)}catch(e){setError(e instanceof Error?e.message:"Unable to create device")}}
 const status=async(d:IotDevice,s:IotDeviceStatus)=>{await updateIotDevice(d.id,{status:s});await load(search)};
 return <section className="module-page iot-page">
  <div className="module-heading"><div><span className="page-eyebrow">CONNECTED OPERATIONS</span><h1>IoT & Management Dashboard</h1><p>Monitor connected equipment, sensor readings, alerts and enterprise KPIs.</p></div><div className="iot-actions"><button className="secondary-action" onClick={()=>void load(search)}><RefreshCw size={18}/> Refresh</button><button className="primary-action" onClick={()=>setShow(true)}><Plus size={18}/> Register device</button></div></div>
  {error&&<div className="page-error">{error}</div>}
  <div className="iot-summary-grid">{[
   ["Devices",data?.iot.devices??0,Wifi],["Online",data?.iot.online??0,Activity],["Offline",data?.iot.offline??0,WifiOff],["Open alerts",data?.iot.openAlerts??0,AlertTriangle],["Active production",data?.business.production??0,Factory]
   ].map((item)=><article key={String(item[0])}>{(()=>{const Icon=item[2] as typeof Wifi;return <Icon size={23}/>})()}<div><strong>{String(item[1])}</strong><span>{String(item[0])}</span></div></article>)}</div>
  <div className="management-grid">
   <div className="directory-card"><div className="directory-header"><div><h2>Enterprise snapshot</h2><p>Live ERP operational indicators</p></div></div><div className="business-kpis">{data&&Object.entries(data.business).map(([k,v])=><div key={k}><strong>{v}</strong><span>{k.replace(/([A-Z])/g," $1").replace(/^./,c=>c.toUpperCase())}</span></div>)}</div></div>
   <div className="directory-card"><div className="directory-header"><div><h2>Recent alerts</h2><p>{data?.recentAlerts.length??0} recent events</p></div></div><div className="alert-list">{!data?.recentAlerts.length?<div className="empty-mini">No IoT alerts</div>:data.recentAlerts.map(a=><div key={a.id}><span className={`severity ${a.severity.toLowerCase()}`}>{a.severity}</span><div><b>{a.title}</b><small>{a.device?.name||"Device"} · {a.status}</small></div>{a.status!=="RESOLVED"&&<button onClick={async()=>{await updateIotAlert(a.id,"RESOLVED");await load(search)}}>Resolve</button>}</div>)}</div></div>
  </div>
  <div className="directory-card"><div className="directory-header"><div><h2>Device registry</h2><p>{devices.length} connected assets</p></div><form className="directory-search" onSubmit={e=>{e.preventDefault();void load(search)}}><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search device..."/><button>Search</button></form></div>
  {loading?<div className="empty-state">Loading connected operations...</div>:devices.length===0?<div className="empty-state"><Wifi size={34}/><h3>No IoT devices registered</h3><p>Register your first gateway or industrial sensor.</p></div>:<div className="table-scroll"><table className="data-table"><thead><tr><th>Device</th><th>Type / Location</th><th>Latest reading</th><th>Last seen</th><th>Status</th><th></th></tr></thead><tbody>{devices.map(d=><tr key={d.id}><td><strong>{d.deviceCode}</strong><small>{d.name}</small></td><td>{d.deviceType}<small>{d.location||"No location"}</small></td><td>{d.readings[0]?`${d.readings[0].sensorType}: ${d.readings[0].value} ${d.readings[0].unit}`:"No readings"}</td><td>{d.lastSeenAt?new Date(d.lastSeenAt).toLocaleString("en-IN"):"Never"}</td><td><select value={d.status} onChange={e=>void status(d,e.target.value as IotDeviceStatus)}>{["ONLINE","OFFLINE","WARNING","MAINTENANCE","DISABLED"].map(s=><option key={s}>{s}</option>)}</select></td><td><button className="row-action-button" onClick={()=>setSelected(d)}>Manage</button></td></tr>)}</tbody></table></div>}</div>
  {show&&<div className="modal-backdrop" onMouseDown={()=>setShow(false)}><div className="iot-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><span className="page-eyebrow">DEVICE REGISTRY</span><h2>Register IoT device</h2></div><button className="icon-button" onClick={()=>setShow(false)}><X/></button></div><form onSubmit={create}><label>Device code<input required value={code} onChange={e=>setCode(e.target.value)} placeholder="IOT-001"/></label><label>Device name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Device type<input required value={type} onChange={e=>setType(e.target.value)}/></label><label>Location<input value={location} onChange={e=>setLocation(e.target.value)}/></label><div className="modal-actions"><button type="button" className="secondary-action" onClick={()=>setShow(false)}>Cancel</button><button className="primary-action">Register device</button></div></form></div></div>}
  {selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><div className="iot-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><span className="page-eyebrow">DEVICE TELEMETRY</span><h2>{selected.name}</h2><p>{selected.deviceCode}</p></div><button className="icon-button" onClick={()=>setSelected(null)}><X/></button></div><div className="iot-manage"><form onSubmit={async e=>{e.preventDefault();await addSensorReading(selected.id,{sensorType:sensor,value:Number(value),unit});setValue("");setSelected(null);await load(search)}}><h3>Add sensor reading</h3><input required value={sensor} onChange={e=>setSensor(e.target.value)} placeholder="Sensor type"/><input required type="number" step="any" value={value} onChange={e=>setValue(e.target.value)} placeholder="Value"/><input required value={unit} onChange={e=>setUnit(e.target.value)} placeholder="Unit"/><button className="primary-action">Record reading</button></form><form onSubmit={async e=>{e.preventDefault();await createIotAlert(selected.id,{title:alertTitle,severity:"WARNING"});setAlertTitle("");setSelected(null);await load(search)}}><h3>Create alert</h3><input required value={alertTitle} onChange={e=>setAlertTitle(e.target.value)} placeholder="Alert title"/><button className="secondary-action">Create warning alert</button></form></div></div></div>}
 </section>
}

