import { useEffect, useState } from "react";
import { ArrowLeft, Plus, RefreshCw } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { getLead, getLeadCrmDetails, saveLeadTechnical, addLeadActivity, addLeadCompetitor, addLeadSurvey, addLeadTender, addLeadOutcome } from "../services/lead.service";
import type { Lead } from "../types/lead";
import "./LeadCRMPage.css";

const sources=["Website Inquiry","IndiaMART","TradeIndia","Export Inquiry","Direct Sales Team","Dealer Network","Reference"];
const industries=["Textile","Chemical","Pharmaceutical","Food","Dairy","Plywood","Paper","Distillery","Rice Mill","Edible Oil"];
const competitors=["Thermax","Forbes Marshall","Balkrishna","Cheema","Others"];
const stages=["LEAD_RECEIVED","SALES_EXECUTIVE_ASSIGNMENT","REQUIREMENT_ANALYSIS","TECHNICAL_DISCUSSION","BUDGETARY_OFFER","COMMERCIAL_OFFER","NEGOTIATION","ORDER_CONFIRMATION"];

export default function LeadCRMPage(){
 const {id=""}=useParams(); const nav=useNavigate(); const [lead,setLead]=useState<Lead|null>(null); const [data,setData]=useState<any>(null); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
 const [tech,setTech]=useState<any>({}); const [activity,setActivity]=useState({type:"FOLLOW_UP",status:"PLANNED",subject:"",notes:"",scheduledAt:""}); const [comp,setComp]=useState({name:"Thermax",notes:"",quotedValue:""}); const [survey,setSurvey]=useState<any>({siteAudit:false,utilityAudit:false,fuelAudit:false,waterAudit:false,status:"DRAFT"}); const [tender,setTender]=useState({tenderNumber:"",dueDate:"",emdAmount:"",bgAmount:"",status:"RECEIVED",technicalClarifications:"",negotiationNotes:"",notes:""}); const [outcome,setOutcome]=useState({outcome:"WON",reason:"",notes:""});
 const load=async()=>{try{setError("");const [l,d]=await Promise.all([getLead(id),getLeadCrmDetails(id)]);setLead(l);setData(d);setTech(d.technical||{});}catch(e){setError(e instanceof Error?e.message:"Unable to load CRM");}};
 useEffect(()=>{void load();},[id]);
 const save=async(fn:()=>Promise<unknown>)=>{try{setSaving(true);setError("");await fn();await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save");}finally{setSaving(false);}};
 if(!lead||!data)return <section className="module-page"><div className="module-heading"><div><span className="page-eyebrow">CRM 360</span><h1>Lead workspace</h1></div><button className="secondary-action" onClick={()=>nav("/leads")}><ArrowLeft size={18}/> Back</button></div>{error?<div className="page-error">{error}</div>:<div className="empty-state">Loading CRM workspace...</div>}</section>;
 return <section className="module-page lead-crm-page"><div className="module-heading"><div><span className="page-eyebrow">CRM 360 • {lead.leadNumber}</span><h1>{lead.title}</h1><p>{lead.customer.companyName}</p></div><div className="crm-heading-actions"><button className="secondary-action" onClick={()=>void load()}><RefreshCw size={17}/> Refresh</button><button className="secondary-action" onClick={()=>nav("/leads")}><ArrowLeft size={17}/> Back</button></div></div>{error&&<div className="page-error">{error}</div>}
 <div className="crm-grid">
  <article className="directory-card"><div className="crm-card-title"><h2>Lead pipeline</h2><span>PRD flow</span></div><select value={tech.crmStage||"LEAD_RECEIVED"} onChange={e=>setTech({...tech,crmStage:e.target.value})}>{stages.map(s=><option key={s}>{s.replaceAll("_"," ")}</option>)}</select><p className="muted">Lead Received → Assignment → Requirement Analysis → Technical Discussion → Budgetary Offer → Commercial Offer → Negotiation → Order Confirmation</p></article>
  <article className="directory-card"><div className="crm-card-title"><h2>Technical qualification</h2><span>Required fields</span></div><div className="crm-form-grid">{[["steamCapacityTph","Steam Capacity (TPH)"],["workingPressureBar","Working Pressure (bar)"],["steamConsumption","Steam Consumption"],["operatingHoursPerDay","Operating Hours / Day"],["existingFuelCost","Existing Fuel Cost"],["fuelType","Fuel Type"],["feedWaterSource","Feed Water Source"]].map(([k,l])=><label key={k}>{l}<input value={tech[k]??""} onChange={e=>setTech({...tech,[k]:e.target.value})}/></label>)}<label>Industry Type<select value={tech.industryType??""} onChange={e=>setTech({...tech,industryType:e.target.value})}><option value="">Select</option>{industries.map(x=><option key={x}>{x}</option>)}</select></label></div><button className="primary-action" disabled={saving} onClick={()=>void save(()=>saveLeadTechnical(id,tech))}>Save qualification</button></article>
  <article className="directory-card"><div className="crm-card-title"><h2>Lead source</h2></div><select value={lead.source||""} disabled><option value="">Not set</option>{sources.map(x=><option key={x}>{x}</option>)}</select><p className="muted">Available PRD sources: {sources.join(", ")}</p></article>
  <article className="directory-card"><div className="crm-card-title"><h2>Follow-up / calls / meetings</h2></div><div className="crm-form-grid"><label>Type<select value={activity.type} onChange={e=>setActivity({...activity,type:e.target.value})}><option>FOLLOW_UP</option><option>CALL</option><option>MEETING</option></select></label><label>Subject<input value={activity.subject} onChange={e=>setActivity({...activity,subject:e.target.value})}/></label><label>Scheduled<input type="datetime-local" value={activity.scheduledAt} onChange={e=>setActivity({...activity,scheduledAt:e.target.value})}/></label><label>Notes<textarea value={activity.notes} onChange={e=>setActivity({...activity,notes:e.target.value})}/></label></div><button className="primary-action" onClick={()=>void save(async()=>{await addLeadActivity(id,activity);setActivity({...activity,subject:"",notes:""});})}><Plus size={17}/> Add activity</button><div className="crm-list">{data.activities.map((x:any)=><div key={x.id}><strong>{x.type}: {x.subject}</strong><span>{x.notes||""}</span></div>)}</div></article>
  <article className="directory-card"><div className="crm-card-title"><h2>Competitor tracking</h2></div><div className="crm-form-grid"><label>Competitor<select value={comp.name} onChange={e=>setComp({...comp,name:e.target.value})}>{competitors.map(x=><option key={x}>{x}</option>)}</select></label><label>Quoted Value<input value={comp.quotedValue} onChange={e=>setComp({...comp,quotedValue:e.target.value})}/></label><label>Notes<textarea value={comp.notes} onChange={e=>setComp({...comp,notes:e.target.value})}/></label></div><button className="primary-action" onClick={()=>void save(async()=>{await addLeadCompetitor(id,comp);setComp({...comp,notes:"",quotedValue:""});})}><Plus size={17}/> Add competitor</button><div className="crm-list">{data.competitors.map((x:any)=><div key={x.id}><strong>{x.name}</strong><span>{x.notes||""}</span></div>)}</div></article>
  <article className="directory-card"><div className="crm-card-title"><h2>Technical survey</h2><span>Engineer visit → audit → report → proposal</span></div><div className="crm-checks">{[["siteAudit","Site Audit"],["utilityAudit","Utility Audit"],["fuelAudit","Fuel Audit"],["waterAudit","Water Audit"]].map(([k,l])=><label key={k}><input type="checkbox" checked={!!survey[k]} onChange={e=>setSurvey({...survey,[k]:e.target.checked})}/>{l}</label>)}</div><div className="crm-form-grid"><label>Engineer Visit<input type="datetime-local" value={survey.engineerVisitAt||""} onChange={e=>setSurvey({...survey,engineerVisitAt:e.target.value})}/></label><label>Chimney Height (m)<input value={survey.chimneyHeightM||""} onChange={e=>setSurvey({...survey,chimneyHeightM:e.target.value})}/></label><label>Boiler Room Layout<textarea value={survey.boilerRoomLayout||""} onChange={e=>setSurvey({...survey,boilerRoomLayout:e.target.value})}/></label><label>Water Analysis<textarea value={survey.waterAnalysis||""} onChange={e=>setSurvey({...survey,waterAnalysis:e.target.value})}/></label><label>Existing Steam Network<textarea value={survey.existingSteamNetwork||""} onChange={e=>setSurvey({...survey,existingSteamNetwork:e.target.value})}/></label><label>Fuel Storage<textarea value={survey.fuelStorage||""} onChange={e=>setSurvey({...survey,fuelStorage:e.target.value})}/></label><label>Survey Report<textarea value={survey.surveyReport||""} onChange={e=>setSurvey({...survey,surveyReport:e.target.value})}/></label><label>Proposal Reference<input value={survey.proposalReference||""} onChange={e=>setSurvey({...survey,proposalReference:e.target.value})}/></label></div><button className="primary-action" onClick={()=>void save(async()=>{await addLeadSurvey(id,survey);})}>Save survey</button></article>
  <article className="directory-card"><div className="crm-card-title"><h2>Tender management</h2><span>Eligibility → EMD → Technical → Commercial → Negotiation → Award</span></div><div className="crm-form-grid"><label>Tender Number<input value={tender.tenderNumber} onChange={e=>setTender({...tender,tenderNumber:e.target.value})}/></label><label>Due Date<input type="date" value={tender.dueDate} onChange={e=>setTender({...tender,dueDate:e.target.value})}/></label><label>EMD Amount<input value={tender.emdAmount} onChange={e=>setTender({...tender,emdAmount:e.target.value})}/></label><label>BG Amount<input value={tender.bgAmount} onChange={e=>setTender({...tender,bgAmount:e.target.value})}/></label><label>Status<select value={tender.status} onChange={e=>setTender({...tender,status:e.target.value})}>{["RECEIVED","ELIGIBILITY_CHECK","EMD_SUBMISSION","TECHNICAL_BID","COMMERCIAL_BID","NEGOTIATION","AWARD","LOST","CANCELLED"].map(x=><option key={x}>{x}</option>)}</select></label><label>Technical Clarifications<textarea value={tender.technicalClarifications} onChange={e=>setTender({...tender,technicalClarifications:e.target.value})}/></label></div><button className="primary-action" onClick={()=>void save(async()=>{await addLeadTender(id,tender);setTender({...tender,tenderNumber:"",dueDate:"",emdAmount:"",bgAmount:"",technicalClarifications:""});})}>Add tender</button><div className="crm-list">{data.tenders.map((x:any)=><div key={x.id}><strong>{x.tenderNumber}</strong><span>{x.status} • Due {x.dueDate?new Date(x.dueDate).toLocaleDateString():"—"}</span></div>)}</div></article>
  <article className="directory-card"><div className="crm-card-title"><h2>Quotation history</h2></div><div className="crm-list">{data.quotations.length?data.quotations.map((x:any)=><div key={x.id}><strong>{x.quotationNumber} v{x.version}</strong><span>{x.status} • ₹{Number(x.totalAmount||0).toLocaleString("en-IN")}</span></div>):<p className="muted">No quotations linked to this lead yet.</p>}</div></article>
  <article className="directory-card"><div className="crm-card-title"><h2>Win / Loss</h2></div><div className="crm-form-grid"><label>Outcome<select value={outcome.outcome} onChange={e=>setOutcome({...outcome,outcome:e.target.value})}><option>WON</option><option>LOST</option><option>ON_HOLD</option></select></label><label>Reason<textarea value={outcome.reason} onChange={e=>setOutcome({...outcome,reason:e.target.value})}/></label><label>Notes<textarea value={outcome.notes} onChange={e=>setOutcome({...outcome,notes:e.target.value})}/></label></div><button className="primary-action" onClick={()=>void save(async()=>{await addLeadOutcome(id,outcome);})}>Record outcome</button></article>
 </div></section>
}
