import {useMemo,useState} from "react";
import {Clock3,PackageOpen,Plus} from "lucide-react";
import {createTraceability,getProductionInventory,recordDowntime,recordMaterialMovement} from "../services/production.service";
import type {MaterialConsumptionType,ProductionInventoryItem,ProductionOrder} from "../types/production";

export default function ProductionTraceabilityPanel({order,onRefresh}:{order:ProductionOrder;onRefresh:()=>Promise<void>}){
 const[items,setItems]=useState<ProductionInventoryItem[]>([]),[showMaterial,setShowMaterial]=useState(false),[showTrace,setShowTrace]=useState(false),[showDown,setShowDown]=useState(false),[error,setError]=useState("");
 const[itemId,setItemId]=useState(""),[move,setMove]=useState<MaterialConsumptionType>("ISSUE"),[qty,setQty]=useState("1"),[heat,setHeat]=useState(""),[batch,setBatch]=useState(""),[serial,setSerial]=useState(""),[mtc,setMtc]=useState("");
 const[component,setComponent]=useState(""),[unit,setUnit]=useState("Nos"),[opId,setOpId]=useState("");
 const[category,setCategory]=useState("BREAKDOWN"),[reason,setReason]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState("");
 const loadItems=async()=>{try{setItems(await getProductionInventory())}catch(e){setError(e instanceof Error?e.message:"Unable to load inventory")}};
 const metrics=useMemo(()=>{const planned=order.operations.reduce((s,o)=>s+Number(o.plannedHours||0),0)*60;const actual=order.operations.reduce((s,o)=>s+Number(o.actualHours||0),0)*60;const down=order.downtimeRecords.reduce((s,d)=>s+d.durationMinutes,0);const produced=Number(order.producedQuantity),bad=Number(order.rejectedQuantity)+Number(order.scrapQuantity);const availability=planned?Math.max(0,Math.min(100,(planned-down)/planned*100)):0;const performance=planned&&actual?Math.min(100,planned/actual*100):0;const quality=produced+bad?produced/(produced+bad)*100:100;return{availability,performance,quality,oee:availability*performance*quality/10000,down}},[order]);
 return <div className="trace-panel">
  <h3>Manufacturing traceability & OEE</h3>
  <div className="oee-grid"><span>Availability<strong>{metrics.availability.toFixed(1)}%</strong></span><span>Performance<strong>{metrics.performance.toFixed(1)}%</strong></span><span>Quality<strong>{metrics.quality.toFixed(1)}%</strong></span><span>OEE<strong>{metrics.oee.toFixed(1)}%</strong></span><span>Downtime<strong>{metrics.down} min</strong></span></div>
  {error&&<div className="page-error">{error}</div>}
  <div className="trace-actions"><button className="secondary-action compact" onClick={()=>{void loadItems();setShowMaterial(!showMaterial)}}><PackageOpen size={15}/> Material movement</button><button className="secondary-action compact" onClick={()=>{void loadItems();setShowTrace(!showTrace)}}><Plus size={15}/> Traceability</button><button className="secondary-action compact" onClick={()=>setShowDown(!showDown)}><Clock3 size={15}/> Downtime</button></div>
  {showMaterial&&<form className="trace-form" onSubmit={async e=>{e.preventDefault();try{await recordMaterialMovement(order.id,{inventoryItemId:itemId,movementType:move,quantity:Number(qty),...(heat?{heatNumber:heat}:{}),...(batch?{batchNumber:batch}:{}),...(serial?{serialNumber:serial}:{}),...(mtc?{materialCertificateNumber:mtc}:{})});setShowMaterial(false);await onRefresh()}catch(e){setError(e instanceof Error?e.message:"Unable to record material")}}}><select required value={itemId} onChange={e=>setItemId(e.target.value)}><option value="">Inventory item</option>{items.map(i=><option key={i.id} value={i.id}>{i.itemCode} — {i.name} ({i.currentStock} {i.unit})</option>)}</select><select value={move} onChange={e=>setMove(e.target.value as MaterialConsumptionType)}><option>ISSUE</option><option>CONSUMPTION</option><option>RETURN</option><option>SCRAP</option></select><input required type="number" min=".001" step=".001" value={qty} onChange={e=>setQty(e.target.value)} placeholder="Quantity"/><input value={heat} onChange={e=>setHeat(e.target.value)} placeholder="Heat no."/><input value={batch} onChange={e=>setBatch(e.target.value)} placeholder="Batch no."/><input value={serial} onChange={e=>setSerial(e.target.value)} placeholder="Serial no."/><input value={mtc} onChange={e=>setMtc(e.target.value)} placeholder="MTC / certificate no."/><button className="primary-action">Save movement</button></form>}
  {showTrace&&<form className="trace-form" onSubmit={async e=>{e.preventDefault();try{await createTraceability(order.id,{operationId:opId||null,inventoryItemId:itemId||null,componentName:component,quantity:Number(qty),unit,...(heat?{heatNumber:heat}:{}),...(batch?{batchNumber:batch}:{}),...(serial?{serialNumber:serial}:{}),...(mtc?{materialCertificateNumber:mtc}:{})});setShowTrace(false);await onRefresh()}catch(e){setError(e instanceof Error?e.message:"Unable to save traceability")}}}><select value={opId} onChange={e=>setOpId(e.target.value)}><option value="">General / whole order</option>{order.operations.map(o=><option key={o.id} value={o.id}>{o.sequence}. {o.name}</option>)}</select><input required value={component} onChange={e=>setComponent(e.target.value)} placeholder="Component / tube / plate"/><input type="number" min=".001" step=".001" required value={qty} onChange={e=>setQty(e.target.value)}/><input required value={unit} onChange={e=>setUnit(e.target.value)} placeholder="Unit"/><input value={heat} onChange={e=>setHeat(e.target.value)} placeholder="Heat no."/><input value={batch} onChange={e=>setBatch(e.target.value)} placeholder="Batch no."/><input value={serial} onChange={e=>setSerial(e.target.value)} placeholder="Serial no."/><input value={mtc} onChange={e=>setMtc(e.target.value)} placeholder="MTC no."/><button className="primary-action">Save traceability</button></form>}
  {showDown&&<form className="trace-form" onSubmit={async e=>{e.preventDefault();try{await recordDowntime(order.id,{operationId:opId||null,category,reason,startedAt:new Date(start).toISOString(),endedAt:new Date(end).toISOString()});setShowDown(false);await onRefresh()}catch(e){setError(e instanceof Error?e.message:"Unable to record downtime")}}}><select value={opId} onChange={e=>setOpId(e.target.value)}><option value="">Whole order</option>{order.operations.map(o=><option key={o.id} value={o.id}>{o.sequence}. {o.name}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)}>{["BREAKDOWN","SETUP","MATERIAL_SHORTAGE","POWER","QUALITY","MAINTENANCE","OTHER"].map(x=><option key={x}>{x}</option>)}</select><input required value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason"/><input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/><input required type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/><button className="primary-action">Record downtime</button></form>}
  <div className="trace-lists"><div><h4>Material traceability</h4>{order.traceabilityRecords.length?order.traceabilityRecords.map(t=><small key={t.id}><b>{t.componentName}</b> · Heat {t.heatNumber||"—"} · Batch {t.batchNumber||"—"} · Serial {t.serialNumber||"—"} · MTC {t.materialCertificateNumber||"—"}</small>):<small>No traceability records yet.</small>}</div><div><h4>Downtime history</h4>{order.downtimeRecords.length?order.downtimeRecords.map(d=><small key={d.id}><b>{d.category}</b> · {d.durationMinutes} min · {d.reason}</small>):<small>No downtime recorded.</small>}</div></div>
 </div>
}
