import {useCallback,useEffect,useMemo,useState} from "react";
import type {FormEvent} from "react";
import {AlertCircle,CheckCircle2,ClipboardList,Flag,FolderKanban,Plus,RefreshCw,Search,X} from "lucide-react";
import {createMilestone,createProject,createProjectCost,createProjectTask,getEligibleProjectOrders,getProjectSummary,getProjects,updateMilestone,updateProject,updateProjectTask} from "../services/project.service";
import type {EligibleOrder,Priority,Project} from "../types/project";
import "./ProjectPage.css";
type Tab="projects"|"milestones"|"tasks";
const fmt=(v:string)=>v.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const date=(v?:string|null)=>v?new Date(v).toLocaleDateString("en-IN"):"—";
export default function ProjectPage(){
 const[projects,setProjects]=useState<Project[]>([]),[orders,setOrders]=useState<EligibleOrder[]>([]),[tab,setTab]=useState<Tab>("projects"),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[success,setSuccess]=useState(""),[modal,setModal]=useState<"project"|"milestone"|"task"|null>(null);
 const[selected,setSelected]=useState<any>(null),[costCategory,setCostCategory]=useState("Engineering"),[costDescription,setCostDescription]=useState(""),[plannedCost,setPlannedCost]=useState(""),[actualCost,setActualCost]=useState(""),[projectId,setProjectId]=useState(""),[orderId,setOrderId]=useState(""),[title,setTitle]=useState(""),[priority,setPriority]=useState<Priority>("MEDIUM"),[start,setStart]=useState(""),[end,setEnd]=useState(""),[due,setDue]=useState(""),[department,setDepartment]=useState(""),[milestoneId,setMilestoneId]=useState("");
 const load=useCallback(async()=>{try{setError("");const[p,o]=await Promise.all([getProjects(),getEligibleProjectOrders()]);setProjects(p);setOrders(o)}catch(e){setError(e instanceof Error?e.message:"Unable to load projects")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const milestones=useMemo(()=>projects.flatMap(p=>p.milestones.map(m=>({...m,projectNumber:p.projectNumber,projectTitle:p.title}))),[projects]);
 const tasks=useMemo(()=>projects.flatMap(p=>p.tasks.map(t=>({...t,projectNumber:p.projectNumber,projectTitle:p.title}))),[projects]);const q=search.toLowerCase();
 const ps=projects.filter(p=>`${p.projectNumber} ${p.title} ${p.customer.companyName} ${p.status}`.toLowerCase().includes(q)),ms=milestones.filter(m=>`${m.name} ${m.projectNumber} ${m.status}`.toLowerCase().includes(q)),ts=tasks.filter(t=>`${t.title} ${t.projectNumber} ${t.department??""} ${t.status}`.toLowerCase().includes(q));
 async function save(e:FormEvent){e.preventDefault();try{setError("");if(modal==="project")await createProject({salesOrderId:orderId,title,priority,...(start?{plannedStartDate:start}:{}),...(end?{plannedEndDate:end}:{})});if(modal==="milestone")await createMilestone({projectId,name:title,...(due?{plannedDate:due}:{})});if(modal==="task")await createProjectTask({projectId,title,priority,...(milestoneId?{milestoneId}:{}),...(department?{department}:{}),...(due?{dueDate:due}:{})});setModal(null);setSuccess(`${modal==="project"?"Project":modal==="milestone"?"Milestone":"Task"} created successfully.`);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save")}}
 function open(m:"project"|"milestone"|"task"){setModal(m);setTitle("");setProjectId("");setOrderId("");setMilestoneId("");setDepartment("");setDue("");setStart("");setEnd("");setPriority("MEDIUM");setError("");setSuccess("")}
 if(loading)return <div className="pm-page"><div className="pm-card pm-empty">Loading projects...</div></div>;
 return <div className="pm-page"><header className="pm-header"><div><span>PROJECT CONTROL</span><h1>Projects & Milestones</h1><p>Plan, track and control customer projects from confirmed sales order to completion.</p></div><div className="pm-actions"><button className="pm-secondary" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button><button className="pm-primary" onClick={()=>open(tab==="projects"?"project":tab==="milestones"?"milestone":"task")}><Plus size={16}/>{tab==="projects"?"New Project":tab==="milestones"?"New Milestone":"New Task"}</button></div></header>
 {error&&<div className="pm-alert error"><AlertCircle size={18}/>{error}</div>}{success&&<div className="pm-alert success"><CheckCircle2 size={18}/>{success}</div>}
 <div className="pm-stats"><Stat label="Total Projects" value={projects.length} icon={<FolderKanban/>}/><Stat label="Active" value={projects.filter(p=>p.status==="ACTIVE").length} icon={<Flag/>}/><Stat label="Open Tasks" value={tasks.filter(t=>!["COMPLETED","CANCELLED"].includes(t.status)).length} icon={<ClipboardList/>}/></div>
 {selected&&<section className="pm-card" style={{marginBottom:16}}><div className="pm-toolbar"><div><b>{selected.projectNumber} — Project Control</b><div className="pm-muted">Stage: {fmt(selected.stage)} · Progress: {Math.round(Number(selected.progressPercent))}% · Delay: {selected.delayDays} day(s)</div></div><button className="pm-secondary" onClick={()=>setSelected(null)}>Close</button></div><div className="pm-stats"><Stat label="Revenue" value={Number(selected.revenueAmount)} icon={<Flag/>}/><Stat label="Actual Cost" value={Number(selected.actualCost)} icon={<ClipboardList/>}/><Stat label="Profit" value={Number(selected.profit)} icon={<CheckCircle2/>}/></div><form onSubmit={async e=>{e.preventDefault();if(!projectId||!costDescription)return;await createProjectCost({projectId,category:costCategory,description:costDescription,plannedCost:Number(plannedCost||0),actualCost:Number(actualCost||0)});setSuccess("Project cost added.");setCostDescription("");setPlannedCost("");setActualCost("");setSelected(await getProjectSummary(projectId));await load()}}><div className="pm-two"><Field label="Cost Category"><select value={costCategory} onChange={e=>setCostCategory(e.target.value)}>{["Engineering","Procurement","Fabrication","Testing","Dispatch","Installation","Commissioning","Other"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Description"><input required value={costDescription} onChange={e=>setCostDescription(e.target.value)} placeholder="e.g. Tube procurement"/></Field></div><div className="pm-two"><Field label="Planned Cost"><input type="number" min="0" value={plannedCost} onChange={e=>setPlannedCost(e.target.value)}/></Field><Field label="Actual Cost"><input type="number" min="0" value={actualCost} onChange={e=>setActualCost(e.target.value)}/></Field></div><button className="pm-primary" type="submit">Add Cost</button></form></section>}
 <section className="pm-card"><div className="pm-toolbar"><div className="pm-tabs">{(["projects","milestones","tasks"] as Tab[]).map(t=><button key={t} className={`pm-tab ${tab===t?"active":""}`} onClick={()=>setTab(t)}>{fmt(t)}</button>)}</div><div className="pm-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${tab}...`}/></div></div>
 <div className="pm-table-wrap"><table className="pm-table"><thead><tr>{(tab==="projects"?["Project","Customer","Sales Order","End Date","Progress","Status","Action"]:tab==="milestones"?["Milestone","Project","Planned Date","Progress","Status","Action"]:["Task","Project","Department","Due Date","Priority","Status","Action"]).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>
 {tab==="projects"&&ps.map(p=><tr key={p.id}><td><b>{p.projectNumber}</b><small>{p.title}</small><button className="pm-mini" onClick={async()=>{setProjectId(p.id);setSelected(await getProjectSummary(p.id))}}>Control</button></td><td>{p.customer.companyName}</td><td>{p.salesOrder.salesOrderNumber}</td><td>{date(p.plannedEndDate)}</td><td><Progress v={Number(p.progressPercent)}/></td><td><Badge v={p.stage}/></td><td><Badge v={p.status}/></td><td>{p.status==="PLANNED"?<button className="pm-mini" onClick={()=>void updateProject(p.id,{status:"ACTIVE"}).then(load)}>Start</button>:p.status==="ACTIVE"?<button className="pm-mini" onClick={()=>void updateProject(p.id,{status:"COMPLETED"}).then(load)}>Complete</button>:"—"}</td></tr>)}
 {tab==="milestones"&&ms.map(m=><tr key={m.id}><td><b>{m.name}</b></td><td>{m.projectNumber}</td><td>{date(m.plannedDate)}</td><td><Progress v={Number(m.progressPercent)}/></td><td><Badge v={m.status}/></td><td>{m.status!=="COMPLETED"&&m.status!=="CANCELLED"?<button className="pm-mini" onClick={()=>void updateMilestone(m.id,{status:"COMPLETED"}).then(load)}>Complete</button>:"—"}</td></tr>)}
 {tab==="tasks"&&ts.map(t=><tr key={t.id}><td><b>{t.title}</b></td><td>{t.projectNumber}</td><td>{t.department??"—"}</td><td>{date(t.dueDate)}</td><td><Badge v={t.priority}/></td><td><Badge v={t.status}/></td><td>{t.status==="TODO"?<button className="pm-mini" onClick={()=>void updateProjectTask(t.id,{status:"IN_PROGRESS"}).then(load)}>Start</button>:t.status==="IN_PROGRESS"||t.status==="BLOCKED"?<button className="pm-mini" onClick={()=>void updateProjectTask(t.id,{status:"COMPLETED"}).then(load)}>Complete</button>:"—"}</td></tr>)}
 </tbody></table>{(tab==="projects"?ps.length:tab==="milestones"?ms.length:ts.length)===0&&<div className="pm-empty">No {tab} found.</div>}</div></section>
 {modal&&<div className="pm-overlay"><div className="pm-modal"><div className="pm-modal-head"><h2>{modal==="project"?"New Project":modal==="milestone"?"New Milestone":"New Task"}</h2><button onClick={()=>setModal(null)}><X/></button></div><form onSubmit={save}>
 {modal==="project"&&<><Field label="Confirmed Sales Order *"><select required value={orderId} onChange={e=>setOrderId(e.target.value)}><option value="">Select sales order</option>{orders.map(o=><option key={o.id} value={o.id}>{o.salesOrderNumber} — {o.customer.companyName}</option>)}</select></Field><Field label="Project Title *"><input required value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Priority"><select value={priority} onChange={e=>setPriority(e.target.value as Priority)}>{["LOW","MEDIUM","HIGH","URGENT"].map(x=><option key={x}>{x}</option>)}</select></Field><div className="pm-two"><Field label="Planned Start"><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Planned End"><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></Field></div></>}
 {modal==="milestone"&&<><ProjectSelect projects={projects} value={projectId} set={setProjectId}/><Field label="Milestone Name *"><input required value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Planned Date"><input type="date" value={due} onChange={e=>setDue(e.target.value)}/></Field></>}
 {modal==="task"&&<><ProjectSelect projects={projects} value={projectId} set={v=>{setProjectId(v);setMilestoneId("")}}/><Field label="Milestone"><select value={milestoneId} onChange={e=>setMilestoneId(e.target.value)}><option value="">No milestone</option>{projects.find(p=>p.id===projectId)?.milestones.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Task Title *"><input required value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Department"><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Select department</option>{["Engineering","Procurement","Production","Quality","Dispatch","Installation","Finance"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Due Date"><input type="date" value={due} onChange={e=>setDue(e.target.value)}/></Field></>}
 <div className="pm-submit"><button className="pm-primary" type="submit"><Plus size={16}/>Create</button></div></form></div></div>}</div>
}
function ProjectSelect({projects,value,set}:{projects:Project[];value:string;set:(v:string)=>void}){return <Field label="Project *"><select required value={value} onChange={e=>set(e.target.value)}><option value="">Select project</option>{projects.filter(p=>!["COMPLETED","CANCELLED"].includes(p.status)).map(p=><option key={p.id} value={p.id}>{p.projectNumber} — {p.title}</option>)}</select></Field>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="pm-field"><span>{label}</span>{children}</label>}
function Stat({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <div className="pm-stat"><div><span>{label}</span><strong>{value}</strong></div><i>{icon}</i></div>}
function Badge({v}:{v:string}){return <span className="pm-badge">{fmt(v)}</span>}
function Progress({v}:{v:number}){return <div className="pm-progress"><div><span style={{width:`${Math.min(100,Math.max(0,v))}%`}}/></div><b>{Math.round(v)}%</b></div>}
