import {AlertTriangle,CheckCircle2,FileWarning,Flame,ShieldCheck,TimerReset} from"lucide-react";
import type * as T from"../types/quality";
const old=(s:string|null|undefined)=>!!s&&new Date(s).getTime()<Date.now();
export default function QualityCompliancePanel({ibr,wps,welders,joints,ncrs,capas}:{ibr:T.IbrDocument[];wps:T.WeldingProcedure[];welders:T.WelderQualification[];joints:T.WeldJoint[];ncrs:T.NCR[];capas:T.CAPA[]}){
 const expiredIbr=ibr.filter(x=>old(x.expiryDate)), expiredWps=wps.filter(x=>x.status==="EXPIRED"||old(x.expiryDate)), expiredWelder=welders.filter(x=>x.status==="EXPIRED"||old(x.expiryDate));
 const badJoints=joints.filter(x=>x.status==="REJECTED"||x.status==="REPAIR"), overdueNcr=ncrs.filter(x=>!["CLOSED","CANCELLED"].includes(x.status)&&old(x.dueDate)), overdueCapa=capas.filter(x=>x.status!=="CLOSED"&&old(x.dueDate)), critical=ncrs.filter(x=>x.severity==="CRITICAL"&&!["CLOSED","CANCELLED"].includes(x.status));
 const cards:[[any,string,number],...Array<[any,string,number]>]=[[FileWarning,"Expired IBR",expiredIbr.length],[Flame,"WPS/PQR Attention",expiredWps.length],[ShieldCheck,"Welder Expired",expiredWelder.length],[AlertTriangle,"Rejected/Repair Joints",badJoints.length],[TimerReset,"Overdue NCR/CAPA",overdueNcr.length+overdueCapa.length],[CheckCircle2,"Critical Open NCR",critical.length]];
 const alerts=[...expiredIbr.map(x=>`IBR ${x.documentNumber} expired`),...expiredWps.map(x=>`${x.procedureType} ${x.procedureNumber} needs attention`),...expiredWelder.map(x=>`Welder ${x.welderCode} qualification expired`),...badJoints.map(x=>`Joint ${x.jointNumber}: ${x.status}`),...overdueNcr.map(x=>`${x.ncrNumber} overdue`),...overdueCapa.map(x=>`${x.capaNumber} overdue`),...critical.map(x=>`${x.ncrNumber}: critical NCR open`)];
 return <section className="qc-panel"><div className="qc-head"><div><span>QUALITY COMPLIANCE CONTROL</span><h2>IBR, Welding & Corrective Action Readiness</h2><p>Live control indicators from your existing quality records.</p></div><ShieldCheck/></div><div className="qc-kpis">{cards.map(([I,l,v])=><article className={v?"warn":""} key={l}><I/><div><strong>{v}</strong><span>{l}</span></div></article>)}</div><div className="qc-alerts"><h3>Compliance & quality alerts</h3>{alerts.length?alerts.slice(0,12).map((a,i)=><div key={i}><AlertTriangle size={15}/>{a}</div>):<p><CheckCircle2 size={16}/> No current alerts from recorded data.</p>}</div><small>This dashboard monitors ERP records; it does not itself constitute regulatory approval or certification.</small></section>
}