import {useCallback,useEffect,useMemo,useState} from "react"; import type{FormEvent}from"react"; import{AlertTriangle,CheckCircle2,ClipboardCheck,FileCheck2,Flame,Plus,Search,ShieldCheck,X}from"lucide-react"; import{getProductionOrders}from"../services/production.service"; import * as api from"../services/quality.service"; import type{ProductionOrder}from"../types/production"; import type * as T from"../types/quality"; import"./QualityPage.css"; import QualityCompliancePanel from"./QualityCompliancePanel";
type Tab="inspections"|"itp"|"ibr"|"welding"|"ncr"|"capa"; const fmt=(s:string)=>s.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()); const dt=(s:string|null|undefined)=>s?new Date(s).toLocaleDateString("en-IN"):"—"; const iso=(s:string)=>new Date(`${s}T00:00:00.000Z`).toISOString();
export default function QualityPage(){const[tab,setTab]=useState<Tab>("inspections"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[search,setSearch]=useState(""),[show,setShow]=useState(false),[orders,setOrders]=useState<ProductionOrder[]>([]),[inspections,setInspections]=useState<T.QualityInspection[]>([]),[itps,setItps]=useState<T.InspectionTestPlan[]>([]),[ibr,setIbr]=useState<T.IbrDocument[]>([]),[wps,setWps]=useState<T.WeldingProcedure[]>([]),[welders,setWelders]=useState<T.WelderQualification[]>([]),[joints,setJoints]=useState<T.WeldJoint[]>([]),[ncrs,setNcrs]=useState<T.NCR[]>([]),[capas,setCapas]=useState<T.CAPA[]>([]),[dash,setDash]=useState<T.QualityDashboard|null>(null),[form,setForm]=useState<Record<string,string>>({});
const load=useCallback(async()=>{try{setLoading(true);setError("");const[a,b,c,d,e,f,g,h,i,j]=await Promise.all([api.getQualityInspections(),api.getItps(),api.getIbrDocuments(),api.getWeldingProcedures(),api.getWelderQualifications(),api.getWeldJoints(),api.getNcrs(),api.getCapas(),api.getQualityDashboard(),getProductionOrders()]);setInspections(a);setItps(b);setIbr(c);setWps(d);setWelders(e);setJoints(f);setNcrs(g);setCapas(h);setDash(i);setOrders(j)}catch(e){setError(e instanceof Error?e.message:"Unable to load quality data")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
const filtered=useMemo(()=>{const q=search.toLowerCase();const rows:any[]=tab==="inspections"?inspections:tab==="itp"?itps:tab==="ibr"?ibr:tab==="welding"?joints:tab==="ncr"?ncrs:capas;return rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q))},[tab,search,inspections,itps,ibr,joints,ncrs,capas]);
const change=(k:string,v:string)=>setForm(x=>({...x,[k]:v})); const submit=async(e:FormEvent)=>{e.preventDefault();try{setError("");if(tab==="inspections")await api.createQualityInspection({productionOrderId:form.productionOrderId,inspectionType:(form.inspectionType||"FINAL") as T.QualityInspectionType,...(form.scheduledDate?{scheduledDate:iso(form.scheduledDate)}:{}),checks:[{parameter:"Visual inspection",specification:"Acceptable workmanship"},{parameter:"Functional test",specification:"Functions as approved"},{parameter:"Documentation",specification:"Records complete"}]});else if(tab==="itp")await api.createItp({productionOrderId:form.productionOrderId||null,title:form.title,revision:form.revision||"0",items:[{activity:form.activity||"Inspection activity",acceptanceCriteria:form.criteria||"",inspectionMethod:form.method||"",holdPoint:false,witnessPoint:false}]});else if(tab==="ibr")await api.createIbrDocument({productionOrderId:form.productionOrderId||null,documentType:form.documentType||"OTHER",documentNumber:form.number,title:form.title,revision:form.revision||"0"});else if(tab==="welding"){if(form.kind==="WELDER")await api.createWelderQualification({welderCode:form.code,welderName:form.name,qualificationNumber:form.number,process:form.process,status:"ACTIVE"});else if(form.kind==="JOINT")await api.createWeldJoint({productionOrderId:form.productionOrderId,jointNumber:form.number,status:"PLANNED"});else await api.createWeldingProcedure({procedureType:form.kind||"WPS",procedureNumber:form.number,title:form.title,process:form.process,status:"DRAFT"})}else if(tab==="ncr")await api.createNcr({productionOrderId:form.productionOrderId||null,title:form.title,description:form.description,severity:form.severity||"MINOR"});else await api.createCapa({ncrId:form.ncrId,title:form.title,correctiveAction:form.correctiveAction,status:"OPEN"});setShow(false);setForm({});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to save record")}};
const setInspectionStatus=async(id:string,status:"PASSED"|"FAILED")=>{try{setError("");await api.updateQualityInspection(id,{status});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update inspection")}};
const headers=tab==="inspections"?["Inspection","Production","Type","Status","Action"]:tab==="itp"?["ITP","Title","Revision","Status"]:tab==="ibr"?["Document","Title","Type","Status"]:tab==="welding"?["Weld Joint","Production","Inspection","Status"]:tab==="ncr"?["NCR","Title","Severity","Status"]:["CAPA","Title","Due","Status"];
const cells=(x:any)=>tab==="inspections"?[x.inspectionNumber,x.productionOrder?.productionNumber,fmt(x.inspectionType),fmt(x.status)]:tab==="itp"?[x.itpNumber,x.title,x.revision,fmt(x.status)]:tab==="ibr"?[x.documentNumber,x.title,fmt(x.documentType),fmt(x.status)]:tab==="welding"?[x.jointNumber,x.productionOrder?.productionNumber,x.inspectionMethod||"—",fmt(x.status)]:tab==="ncr"?[x.ncrNumber,x.title,fmt(x.severity),fmt(x.status)]:[x.capaNumber,x.title,dt(x.dueDate),fmt(x.status)];
return <section className="module-page quality-page advanced-quality"><div className="module-heading"><div><span className="page-eyebrow">QUALITY • IBR • WELDING • NCR • CAPA</span><h1>Quality Management</h1><p>Inspection, statutory records, welding traceability and corrective action control.</p></div><button className="primary-action" onClick={()=>setShow(true)}><Plus size={18}/>New {tab.toUpperCase()}</button></div>
<div className="qa-summary">{[["Inspections",dash?.inspections,ClipboardCheck],["ITPs",dash?.itps,FileCheck2],["IBR",dash?.ibr,ShieldCheck],["Weld joints",dash?.joints,Flame],["Open NCR",dash?.openNcrs,AlertTriangle],["Open CAPA",dash?.openCapas,CheckCircle2]].map(([a,b,I]:any)=><article key={a}><I size={22}/><div><strong>{b??0}</strong><span>{a}</span></div></article>)}</div>
<QualityCompliancePanel ibr={ibr} wps={wps} welders={welders} joints={joints} ncrs={ncrs} capas={capas}/><div className="qa-tabs">{(["inspections","itp","ibr","welding","ncr","capa"] as Tab[]).map(t=><button className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t==="itp"?"ITP":t==="ibr"?"IBR":t==="ncr"?"NCR":t==="capa"?"CAPA":fmt(t)}</button>)}</div>
<div className="directory-card"><div className="directory-header"><div><h2>{fmt(tab)} register</h2><p>{filtered.length} records</p></div><div className="directory-search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records..."/></div></div>{error&&<div className="page-error">{error}</div>}{loading?<div className="empty-state">Loading...</div>:<div className="table-scroll"><table className="data-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map((x:any)=><tr key={x.id}>{cells(x).map((c:any,i:number)=><td key={i}>{c??"—"}</td>)}{tab==="inspections"&&<td>{x.status==="PENDING"?<div className="qa-status-actions"><button type="button" className="qa-pass" onClick={()=>void setInspectionStatus(x.id,"PASSED")}>Pass</button><button type="button" className="qa-fail" onClick={()=>void setInspectionStatus(x.id,"FAILED")}>Fail</button></div>:<span>—</span>}</td>}</tr>)}</tbody></table>{!filtered.length&&<div className="empty-state">No records found.</div>}</div>}</div>
{show&&<div className="modal-backdrop"><div className="modal-card qa-modal"><div className="modal-header"><div><h2>New {tab.toUpperCase()}</h2><p>Create a quality-control record.</p></div><button className="icon-button" onClick={()=>setShow(false)}><X/></button></div><form onSubmit={submit}><div className="qa-form">
{["inspections","itp","ibr","welding","ncr"].includes(tab)&&<label>Production order<select value={form.productionOrderId||""} onChange={e=>change("productionOrderId",e.target.value)}><option value="">Select / optional</option>{orders.map(o=><option value={o.id} key={o.id}>{o.productionNumber} — {o.title}</option>)}</select></label>}
{tab==="inspections"&&<><label>Type<select value={form.inspectionType||"FINAL"} onChange={e=>change("inspectionType",e.target.value)}><option>FINAL</option><option>IN_PROCESS</option></select></label><label>Scheduled<input type="date" onChange={e=>change("scheduledDate",e.target.value)}/></label></>}
{tab==="itp"&&<><label>Title<input required onChange={e=>change("title",e.target.value)}/></label><label>Revision<input onChange={e=>change("revision",e.target.value)}/></label><label>Activity<input required onChange={e=>change("activity",e.target.value)}/></label><label>Acceptance criteria<input onChange={e=>change("criteria",e.target.value)}/></label><label>Inspection method<input onChange={e=>change("method",e.target.value)}/></label></>}
{tab==="ibr"&&<><label>Document type<select onChange={e=>change("documentType",e.target.value)}><option>OTHER</option><option>FORM_III</option><option>FORM_IV</option><option>FORM_XVI</option><option>DRAWING</option><option>MATERIAL_CERTIFICATE</option><option>TEST_CERTIFICATE</option></select></label><label>Document number<input required onChange={e=>change("number",e.target.value)}/></label><label>Title<input required onChange={e=>change("title",e.target.value)}/></label></>}
{tab==="welding"&&<><label>Record type<select value={form.kind||"WPS"} onChange={e=>change("kind",e.target.value)}><option>WPS</option><option>PQR</option><option value="WELDER">WPQ / Welder</option><option value="JOINT">Weld Joint</option></select></label>{form.kind==="WELDER"?<><label>Welder code<input required onChange={e=>change("code",e.target.value)}/></label><label>Welder name<input required onChange={e=>change("name",e.target.value)}/></label></>:null}<label>Number<input required onChange={e=>change("number",e.target.value)}/></label>{form.kind!=="JOINT"&&form.kind!=="WELDER"&&<label>Title<input required onChange={e=>change("title",e.target.value)}/></label>}{form.kind!=="JOINT"&&<label>Process<input required onChange={e=>change("process",e.target.value)}/></label>}</>}
{tab==="ncr"&&<><label>Title<input required onChange={e=>change("title",e.target.value)}/></label><label>Severity<select onChange={e=>change("severity",e.target.value)}><option>MINOR</option><option>MAJOR</option><option>CRITICAL</option></select></label><label className="wide">Description<textarea required onChange={e=>change("description",e.target.value)}/></label></>}
{tab==="capa"&&<><label>NCR<select required onChange={e=>change("ncrId",e.target.value)}><option value="">Select NCR</option>{ncrs.filter(n=>n.status!=="CLOSED").map(n=><option value={n.id} key={n.id}>{n.ncrNumber} — {n.title}</option>)}</select></label><label>Title<input required onChange={e=>change("title",e.target.value)}/></label><label className="wide">Corrective action<textarea required onChange={e=>change("correctiveAction",e.target.value)}/></label></>}
</div><div className="qa-actions"><button type="button" onClick={()=>setShow(false)}>Cancel</button><button className="primary-action" type="submit">Create record</button></div></form></div></div>}</section>}
