import { useCallback, useEffect, useMemo, useState } from "react";
import type { FormEvent, ReactNode } from "react";
import { AlertCircle, CheckCircle2, CircleDollarSign, FileText, Plus, RefreshCw, Search, ShoppingBag, Truck, X } from "lucide-react";
import { createDispatchNote, createEWayBill, createSalesInvoice, createSalesOrder, createSalesPayment, getDispatchNotes, getEWayBills, getEligibleSalesQuotations, getSalesInvoices, getSalesOrders, updateSalesInvoice, updateSalesOrder } from "../services/sales.service";
import type { EligibleQuotation, InvoiceType, PaymentMethod, PaymentType, SalesDispatchNote, SalesEWayBill, SalesInvoice, SalesOrder } from "../types/sales";
import "./SalesPage.css";

type Tab = "orders" | "invoices" | "payments" | "dispatch" | "eway";
type Modal = "order" | "invoice" | "payment" | "dispatch" | "eway" | null;
const money=(v:unknown)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(v??0));
const formatDate=(v?:string|null)=>v?new Date(v).toLocaleDateString("en-IN"):"—";
const formatText=(v:string)=>v.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const printDocument=(title:string,html:string)=>{const w=window.open("","_blank","width=900,height=700");if(!w)return;w.document.write(`<!doctype html><html><head><title>${title}</title><style>body{font-family:Arial,sans-serif;padding:40px;color:#222}h1{margin-bottom:4px}table{width:100%;border-collapse:collapse;margin-top:20px}td,th{border:1px solid #ddd;padding:8px;text-align:left} .total{font-size:18px;font-weight:700;margin-top:20px}</style></head><body>${html}</body></html>`);w.document.close();w.focus();w.print();};

export default function SalesPage(){
 const [orders,setOrders]=useState<SalesOrder[]>([]),[invoices,setInvoices]=useState<SalesInvoice[]>([]),[quotes,setQuotes]=useState<EligibleQuotation[]>([]),[dispatchNotes,setDispatchNotes]=useState<SalesDispatchNote[]>([]),[ewayBills,setEwayBills]=useState<SalesEWayBill[]>([]);
 const [tab,setTab]=useState<Tab>("orders"),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[success,setSuccess]=useState(""),[modal,setModal]=useState<Modal>(null);
 const [selectedQuote,setSelectedQuote]=useState(""),[selectedOrder,setSelectedOrder]=useState(""),[selectedInvoice,setSelectedInvoice]=useState(""),[invoiceType,setInvoiceType]=useState<InvoiceType>("TAX"),[paymentType,setPaymentType]=useState<PaymentType>("FINAL"),[po,setPo]=useState(""),[delivery,setDelivery]=useState(""),[due,setDue]=useState(""),[amount,setAmount]=useState(""),[method,setMethod]=useState<PaymentMethod>("BANK_TRANSFER"),[reference,setReference]=useState("");
 const [dispatchStatus,setDispatchStatus]=useState("DRAFT"),[vehicle,setVehicle]=useState(""),[transporter,setTransporter]=useState(""),[lr,setLr]=useState(""),[ewayNumber,setEwayNumber]=useState(""),[distance,setDistance]=useState(""),[ewayValid,setEwayValid]=useState("");
 const load=useCallback(async()=>{try{setError("");const [o,i,q,d,e]=await Promise.all([getSalesOrders(),getSalesInvoices(),getEligibleSalesQuotations(),getDispatchNotes(),getEWayBills()]);setOrders(o);setInvoices(i);setQuotes(q);setDispatchNotes(d);setEwayBills(e);}catch(e){setError(e instanceof Error?e.message:"Unable to load sales data");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const payments=useMemo(()=>invoices.flatMap(i=>i.payments.map(p=>({...p,invoiceNumber:i.invoiceNumber,customer:i.customer.companyName}))),[invoices]);
 const q=search.toLowerCase();
 const orderRows=orders.filter(o=>`${o.salesOrderNumber} ${o.customer.companyName} ${o.status}`.toLowerCase().includes(q));
 const invoiceRows=invoices.filter(i=>`${i.invoiceNumber} ${i.customer.companyName} ${i.status} ${i.type}`.toLowerCase().includes(q));
 const paymentRows=payments.filter(p=>`${p.paymentNumber} ${p.invoiceNumber} ${p.customer} ${p.type??""}`.toLowerCase().includes(q));
 const dispatchRows=dispatchNotes.filter(d=>`${d.dispatchNoteNumber} ${d.salesOrder.salesOrderNumber} ${d.status}`.toLowerCase().includes(q));
 const ewayRows=ewayBills.filter(e=>`${e.eWayBillNumber} ${e.vehicleNumber??""}`.toLowerCase().includes(q));
 const outstanding=invoices.reduce((s,i)=>s+Number(i.balanceAmount),0);
 const clear=()=>{setError("");setSuccess("");};
 const open=(m:Modal)=>{clear();setModal(m);if(m==="order"){setSelectedQuote("");setPo("");setDelivery("");}if(m==="invoice"){setSelectedOrder("");setDue("");setInvoiceType("TAX");}if(m==="payment"){setSelectedInvoice("");setSelectedOrder("");setAmount("");setPaymentType("FINAL");}if(m==="dispatch"){setSelectedOrder("");setVehicle("");setTransporter("");setLr("");setDispatchStatus("DRAFT");}if(m==="eway"){setSelectedOrder("");setEwayNumber("");setVehicle("");setTransporter("");setDistance("");setEwayValid("");}};
 async function saveOrder(e:FormEvent){e.preventDefault();const quote=quotes.find(x=>x.id===selectedQuote);if(!quote?.estimate.lead.customer){setError("Select an accepted quotation with a customer.");return;}try{await createSalesOrder({quotationId:quote.id,customerId:quote.estimate.lead.customer.id,customerPoNumber:po||undefined,expectedDeliveryDate:delivery||undefined,advanceDueAmount:Number(quote.totalAmount)*0.5,paymentTerms:quote.paymentTerms??undefined,deliveryTerms:quote.deliveryTerms??undefined,billingAddress:quote.estimate.lead.customer.billingAddress??undefined,shippingAddress:quote.estimate.lead.customer.shippingAddress??undefined,items:quote.estimate.items.map((x,i)=>({lineNumber:i+1,description:x.description,quantity:Number(x.quantity),unit:x.unit,unitPrice:Number(x.unitRate),taxPercent:Number(quote.taxPercent),discountPercent:0}))});setModal(null);setSuccess("Sales order created successfully.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create sales order");}}
 async function saveInvoice(e:FormEvent){e.preventDefault();try{await createSalesInvoice({salesOrderId:selectedOrder,type:invoiceType,dueDate:due||undefined});setModal(null);setSuccess(`${invoiceType==='PROFORMA'?'Proforma invoice':'Tax invoice'} created successfully.`);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create invoice");}}
 async function savePayment(e:FormEvent){e.preventDefault();if(Number(amount)<=0){setError("Enter a valid amount.");return;}try{if(paymentType==="FINAL"&&!selectedInvoice){setError("Select an invoice for final payment.");return;}if(paymentType!=="FINAL"&&!selectedOrder){setError("Select a sales order for advance/milestone payment.");return;}await createSalesPayment({...(paymentType==="FINAL"?{invoiceId:selectedInvoice}:{salesOrderId:selectedOrder}),type:paymentType,amount:Number(amount),method,referenceNumber:reference||undefined});setModal(null);setSuccess("Payment recorded successfully.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to record payment");}}
 async function saveDispatch(e:FormEvent){e.preventDefault();const o=orders.find(x=>x.id===selectedOrder);if(!o){setError("Select a sales order.");return;}try{await createDispatchNote({salesOrderId:o.id,status:dispatchStatus,vehicleNumber:vehicle||undefined,transporterName:transporter||undefined,lrNumber:lr||undefined,packageCount:1,items:o.items.map((x,i)=>({lineNumber:i+1,description:x.description,quantity:Number(x.quantity),unit:x.unit}))});setModal(null);setSuccess("Dispatch note created successfully.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create dispatch note");}}
 async function saveEway(e:FormEvent){e.preventDefault();try{await createEWayBill({salesOrderId:selectedOrder,eWayBillNumber:ewayNumber,vehicleNumber:vehicle||undefined,transporterName:transporter||undefined,distanceKm:distance?Number(distance):undefined,validUntil:ewayValid||undefined});setModal(null);setSuccess("E-Way Bill recorded successfully.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create E-Way Bill");}}
 async function status(id:string,status:any){try{await updateSalesOrder(id,{status});setSuccess(`Sales order moved to ${formatText(status)}.`);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update sales order");}}
 async function issue(id:string){try{await updateSalesInvoice(id,{status:"ISSUED"});setSuccess("Invoice issued successfully.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to issue invoice");}}
 if(loading)return <div className="sales-page"><div className="sales-card"><div className="sales-empty">Loading sales data...</div></div></div>;
 const visibleCount=tab==="orders"?orderRows.length:tab==="invoices"?invoiceRows.length:tab==="payments"?paymentRows.length:tab==="dispatch"?dispatchRows.length:ewayRows.length;
 return <div className="sales-page">
  <div className="sales-header"><div><span className="sales-eyebrow">SALES CONTROL</span><h1>Sales Management</h1><p>Inquiry → Quotation → Customer Approval → Sales Order → Advance → Production → Dispatch → Installation → Final Payment.</p></div><div className="sales-actions"><button className="sales-secondary-btn" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button>{tab!=="payments"&&<button className="sales-primary-btn" onClick={()=>open(tab==="orders"?"order":tab==="invoices"?"invoice":tab==="dispatch"?"dispatch":"eway")}><Plus size={17}/>New {tab==="orders"?"Sales Order":tab==="invoices"?"Invoice":tab==="dispatch"?"Dispatch Note":"E-Way Bill"}</button>}{tab==="payments"&&<button className="sales-primary-btn" onClick={()=>open("payment")}><Plus size={17}/>Record Payment</button>}</div></div>
  {error&&<div className="sales-alert sales-alert-error"><AlertCircle size={18}/><span>{error}</span></div>}{success&&<div className="sales-alert sales-alert-success"><CheckCircle2 size={18}/><span>{success}</span></div>}
  <div className="sales-summary-grid"><SummaryCard label="Sales Orders" value={orders.length} icon={<ShoppingBag size={21}/>}/><SummaryCard label="Invoices" value={invoices.length} icon={<FileText size={21}/>}/><SummaryCard label="Outstanding" value={money(outstanding)} icon={<CircleDollarSign size={22}/>}/><SummaryCard label="Dispatch Notes" value={dispatchNotes.length} icon={<Truck size={21}/>}/></div>
  <section className="sales-card"><div className="sales-toolbar"><div className="sales-tabs">{(["orders","invoices","payments","dispatch","eway"] as Tab[]).map(t=><button key={t} className={`sales-tab ${tab===t?"active":""}`} onClick={()=>setTab(t)}>{t==="eway"?"E-Way Bills":formatText(t)}</button>)}</div><div className="sales-search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${tab}...`}/></div></div>
   <div className="sales-table-wrap"><table className="sales-table"><thead>{tab==="orders"&&<tr><th>SO</th><th>Customer</th><th>Date</th><th>Total</th><th>Advance</th><th>Status</th><th>Action</th></tr>}{tab==="invoices"&&<tr><th>Invoice</th><th>Type</th><th>Customer</th><th>Total</th><th>Balance</th><th>Status</th><th>Action</th></tr>}{tab==="payments"&&<tr><th>Payment</th><th>Reference</th><th>Type</th><th>Date</th><th>Amount</th><th>Method</th></tr>}{tab==="dispatch"&&<tr><th>Dispatch Note</th><th>SO</th><th>Vehicle</th><th>LR</th><th>Status</th></tr>}{tab==="eway"&&<tr><th>E-Way Bill</th><th>SO</th><th>Vehicle</th><th>Transporter</th><th>Valid Until</th></tr>}</thead><tbody>
   {tab==="orders"&&orderRows.map(o=><tr key={o.id}><td><strong>{o.salesOrderNumber}</strong></td><td>{o.customer.companyName}</td><td>{formatDate(o.orderDate)}</td><td><strong>{money(o.totalAmount)}</strong></td><td>{money(o.advanceAmount)}</td><td><StatusBadge status={o.status}/></td><td><button className="sales-secondary-btn" onClick={()=>printDocument(o.salesOrderNumber,`<h1>Sales Order ${o.salesOrderNumber}</h1><p><b>Customer:</b> ${o.customer.companyName}</p><p><b>Date:</b> ${formatDate(o.orderDate)}</p><table><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Amount</th></tr>${o.items.map(i=>`<tr><td>${i.description}</td><td>${i.quantity}</td><td>${i.unit}</td><td>${money(i.lineTotal)}</td></tr>`).join("")}</table><div class="total">Total: ${money(o.totalAmount)}</div>`)}>Print SO</button>{o.status==="DRAFT"&&<button className="sales-secondary-btn" onClick={()=>void status(o.id,"CONFIRMED")}>Confirm</button>}{o.status==="CONFIRMED"&&<button className="sales-secondary-btn" onClick={()=>void status(o.id,"IN_PRODUCTION")}>Start Production</button>}{o.status==="IN_PRODUCTION"&&<button className="sales-secondary-btn" onClick={()=>void status(o.id,"READY_FOR_DISPATCH")}>Ready Dispatch</button>}{o.status==="READY_FOR_DISPATCH"&&<button className="sales-secondary-btn" onClick={()=>void status(o.id,"DISPATCHED")}>Dispatch</button>}</td></tr>)}
   {tab==="invoices"&&invoiceRows.map(i=><tr key={i.id}><td><strong>{i.invoiceNumber}</strong></td><td>{i.type}</td><td>{i.customer.companyName}</td><td>{money(i.totalAmount)}</td><td>{money(i.balanceAmount)}</td><td><StatusBadge status={i.status}/></td><td><button className="sales-secondary-btn" onClick={()=>printDocument(i.invoiceNumber,`<h1>${i.type} ${i.invoiceNumber}</h1><p><b>Customer:</b> ${i.customer.companyName}</p><p><b>Date:</b> ${formatDate(i.invoiceDate)}</p><div class="total">Total: ${money(i.totalAmount)}</div><div class="total">Balance: ${money(i.balanceAmount)}</div>`)}>Print</button>{i.status==="DRAFT"&&<button className="sales-secondary-btn" onClick={()=>void issue(i.id)}>Issue</button>}</td></tr>)}
   {tab==="payments"&&paymentRows.map(p=><tr key={p.id}><td><strong>{p.paymentNumber}</strong></td><td>{p.invoiceNumber??p.salesOrder?.salesOrderNumber??"—"}</td><td>{formatText(p.type??"FINAL")}</td><td>{formatDate(p.paymentDate)}</td><td><strong>{money(p.amount)}</strong></td><td>{formatText(p.method)}</td></tr>)}
   {tab==="dispatch"&&dispatchRows.map(d=><tr key={d.id}><td><strong>{d.dispatchNoteNumber}</strong></td><td>{d.salesOrder.salesOrderNumber}</td><td>{d.vehicleNumber??"—"}</td><td>{d.lrNumber??"—"}</td><td><StatusBadge status={d.status}/></td></tr>)}
   {tab==="eway"&&ewayRows.map(e=><tr key={e.id}><td><strong>{e.eWayBillNumber}</strong></td><td>{e.salesOrderId.slice(0,8)}</td><td>{e.vehicleNumber??"—"}</td><td>{e.transporterName??"—"}</td><td>{formatDate(e.validUntil)}</td></tr>)}
   </tbody></table>{visibleCount===0&&<div className="sales-empty">No {tab} found.</div>}</div>
  </section>
  {modal&&<div className="sales-modal-overlay"><div className="sales-modal"><div className="sales-modal-header"><h2>{modal==="order"?"New Sales Order":modal==="invoice"?"New Invoice":modal==="payment"?"Record Payment":modal==="dispatch"?"New Dispatch Note":"New E-Way Bill"}</h2><button className="sales-close-btn" onClick={()=>setModal(null)}><X size={19}/></button></div>
   {modal==="order"&&<form onSubmit={saveOrder}><Field label="Accepted Quotation *"><select required value={selectedQuote} onChange={e=>setSelectedQuote(e.target.value)}><option value="">Select quotation</option>{quotes.filter(x=>x.customerApprovalStatus!=="REJECTED").map(x=><option key={x.id} value={x.id}>{x.quotationNumber} — {x.estimate.lead.customer?.companyName??"No customer"} — {money(x.totalAmount)}</option>)}</select></Field><Field label="Customer PO Number"><input value={po} onChange={e=>setPo(e.target.value)}/></Field><Field label="Expected Delivery"><input type="date" value={delivery} onChange={e=>setDelivery(e.target.value)}/></Field><SubmitButton text="Create Sales Order"/></form>}
   {modal==="invoice"&&<form onSubmit={saveInvoice}><Field label="Sales Order *"><select required value={selectedOrder} onChange={e=>setSelectedOrder(e.target.value)}><option value="">Select order</option>{orders.filter(o=>["CONFIRMED","ADVANCE_PENDING","ADVANCE_RECEIVED","IN_PRODUCTION","READY_FOR_DISPATCH"].includes(o.status)&&!o.invoices?.some(i=>i.status!=="CANCELLED"&&i.type===invoiceType)).map(o=><option key={o.id} value={o.id}>{o.salesOrderNumber} — {o.customer.companyName}</option>)}</select></Field><Field label="Invoice Type"><select value={invoiceType} onChange={e=>setInvoiceType(e.target.value as InvoiceType)}><option value="PROFORMA">Proforma Invoice</option><option value="TAX">Tax Invoice</option></select></Field><Field label="Due Date"><input type="date" value={due} onChange={e=>setDue(e.target.value)}/></Field><SubmitButton text={`Create ${invoiceType==="PROFORMA"?"Proforma":"Tax"} Invoice`}/></form>}
   {modal==="payment"&&<form onSubmit={savePayment}><Field label="Payment Type"><select value={paymentType} onChange={e=>setPaymentType(e.target.value as PaymentType)}><option value="ADVANCE">Advance</option><option value="MILESTONE">Milestone</option><option value="FINAL">Final</option></select></Field>{paymentType==="FINAL"?<Field label="Issued Invoice *"><select required value={selectedInvoice} onChange={e=>setSelectedInvoice(e.target.value)}><option value="">Select invoice</option>{invoices.filter(i=>["ISSUED","PARTIALLY_PAID","OVERDUE"].includes(i.status)&&Number(i.balanceAmount)>0).map(i=><option key={i.id} value={i.id}>{i.invoiceNumber} — {money(i.balanceAmount)}</option>)}</select></Field>:<Field label="Sales Order *"><select required value={selectedOrder} onChange={e=>setSelectedOrder(e.target.value)}><option value="">Select order</option>{orders.filter(o=>!(["CLOSED","CANCELLED"].includes(o.status))).map(o=><option key={o.id} value={o.id}>{o.salesOrderNumber} — {o.customer.companyName}</option>)}</select></Field>}<Field label="Amount *"><input required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></Field><Field label="Payment Method"><select value={method} onChange={e=>setMethod(e.target.value as PaymentMethod)}><option value="BANK_TRANSFER">Bank Transfer</option><option value="UPI">UPI</option><option value="CHEQUE">Cheque</option><option value="CASH">Cash</option><option value="CARD">Card</option><option value="OTHER">Other</option></select></Field><Field label="Reference Number"><input value={reference} onChange={e=>setReference(e.target.value)}/></Field><SubmitButton text="Record Payment"/></form>}
   {modal==="dispatch"&&<form onSubmit={saveDispatch}><Field label="Sales Order *"><select required value={selectedOrder} onChange={e=>setSelectedOrder(e.target.value)}><option value="">Select order</option>{orders.filter(o=>["READY_FOR_DISPATCH","DISPATCHED"].includes(o.status)).map(o=><option key={o.id} value={o.id}>{o.salesOrderNumber} — {o.customer.companyName}</option>)}</select></Field><Field label="Status"><select value={dispatchStatus} onChange={e=>setDispatchStatus(e.target.value)}><option value="DRAFT">Draft</option><option value="READY">Ready</option><option value="DISPATCHED">Dispatched</option><option value="DELIVERED">Delivered</option></select></Field><Field label="Vehicle Number"><input value={vehicle} onChange={e=>setVehicle(e.target.value)}/></Field><Field label="Transporter"><input value={transporter} onChange={e=>setTransporter(e.target.value)}/></Field><Field label="LR Number"><input value={lr} onChange={e=>setLr(e.target.value)}/></Field><SubmitButton text="Create Dispatch Note"/></form>}
   {modal==="eway"&&<form onSubmit={saveEway}><Field label="Sales Order *"><select required value={selectedOrder} onChange={e=>setSelectedOrder(e.target.value)}><option value="">Select order</option>{orders.filter(o=>!["CANCELLED","DRAFT"].includes(o.status)).map(o=><option key={o.id} value={o.id}>{o.salesOrderNumber} — {o.customer.companyName}</option>)}</select></Field><Field label="E-Way Bill Number *"><input required value={ewayNumber} onChange={e=>setEwayNumber(e.target.value)}/></Field><Field label="Vehicle Number"><input value={vehicle} onChange={e=>setVehicle(e.target.value)}/></Field><Field label="Transporter"><input value={transporter} onChange={e=>setTransporter(e.target.value)}/></Field><Field label="Distance (KM)"><input type="number" min="0" value={distance} onChange={e=>setDistance(e.target.value)}/></Field><Field label="Valid Until"><input type="date" value={ewayValid} onChange={e=>setEwayValid(e.target.value)}/></Field><SubmitButton text="Record E-Way Bill"/></form>}
  </div></div>}
 </div>;
}
function SummaryCard({label,value,icon}:{label:string;value:string|number;icon:ReactNode}){return <div className="sales-summary-card"><div><span className="sales-summary-label">{label}</span><strong className="sales-summary-value">{value}</strong></div><div className="sales-summary-icon">{icon}</div></div>}
function StatusBadge({status}:{status:string}){return <span className="sales-status">{formatText(status)}</span>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="sales-field"><span>{label}</span>{children}</label>}
function SubmitButton({text}:{text:string}){return <div className="sales-submit"><button className="sales-primary-btn" type="submit"><Plus size={17}/>{text}</button></div>}
